import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  nav: '시작',
  title: 'Coo',
  running: '깨어 있음',
  paused: '일시 중지됨',
  noModel: '연결된 모델 없음',
  modelTitle: '모델 연결',
  modelNeed: (first: string) => `모델 서비스를 고르고 API Key를 입력하면 시작할 수 있습니다. 잘 모르겠으면 ${first}을(를) 고르세요.`,
  more: '더 보기',
  toIntl: '국제 플랫폼 사용',
  toCn: '중국 본토 플랫폼 사용',
  keyLabel: (name: string) => `${name} API Key`,
  modelLabel: '모델',
  keepKey: '비워 두면 저장된 Key를 유지합니다',
  getKey: (name: string) => `${name} Key 발급받기`,
  saveStart: '저장하고 시작',
  connected: (model: string, title: string) => `${title} · ${model}에 연결됨`,
  test: '테스트',
  changeKey: '서비스, 모델 또는 Key 변경',
  otherProvider: '다른 모델 서비스 사용',
  toAdvancedTitle: '고급 모드로 전환하시겠습니까?',
  toAdvancedBody: '다른 모델 서비스는 고급 모드의 모델 페이지에서 설정합니다. 왼쪽 아래에서 일반 모드로 다시 전환할 수 있습니다.',
  testing: '테스트하는 중…',
  testOk: (ms: number | null) => `연결 정상${ms !== null ? `, ${ms} ms` : ''}`,
  testFail: (why: string) => `연결 실패: ${why}`,
  started: '완료. Coo가 깨어났습니다.',
  petTitle: '데스크톱 펫',
  petShown: '바탕 화면에 표시됨',
  petHidden: '표시 안 됨',
  showPet: '펫 표시',
  dress: '꾸미기',
  petNote: '펫에 포인터를 올리면 입력 버튼과 마이크 버튼이 나타납니다. 오른쪽 클릭하면 메뉴가 열리고, 누르고 있으면 들어 올릴 수 있습니다.',
  guide: '사용 안내',
  guideHint: 'Coo가 화면 아래쪽에서 처음부터 다시 안내합니다',
};
