import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  nav: '開始',
  modelTitle: '連線模型',
  modelNeed: (first: string) => `選一家供應商，填入它的 API Key 就能開始。拿不定主意就選 ${first}。`,
  more: '更多',
  toIntl: '改用國際平台',
  toCn: '改用中國大陸平台',
  keyLabel: (name: string) => `${name} 的 API Key`,
  modelLabel: '模型',
  keepKey: '留空沿用已儲存的 Key',
  getKey: (name: string) => `到 ${name} 申請 Key`,
  saveStart: '儲存並開始',
  test: '測試連線',
  otherProvider: '沒找到？手動設定其他模型',
  toAdvancedTitle: '要切換為進階模式嗎？',
  toAdvancedBody: '別的模型服務在進階模式的「模型」頁裡設定。之後可以在左下角切換回一般模式。',
  testing: '正在測試…',
  testOk: (ms: number | null) => `連線正常${ms !== null ? `，耗時 ${ms} ms` : ''}`,
  testFail: (why: string) => `連線失敗：${why}`,
  started: '好了，Coo 醒了。',
  petTitle: '我的桌寵',
  petShown: '在桌面上',
  petHidden: '已隱藏',
  showPet: '在桌面上顯示',
  dress: '裝扮',
  guide: '使用嚮導',
  guideHint: '讓 Coo 在螢幕底邊再帶你走一遍',
  hidePet: '在桌面上隱藏',
  connectedLabel: '已連線的模型：',
  choicesLabel: '可選擇的模型：',
  notConnected: '尚未連線',
  schemeTitle: '配色方案',
};
