import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  nav: 'Начало',
  modelTitle: 'Подключить модель',
  modelNeed: (first: string) => `Выберите поставщика и введите его API Key, чтобы начать. Если не уверены, ${first}.`,
  more: 'Ещё',
  toIntl: 'Использовать международную платформу',
  toCn: 'Использовать платформу для материкового Китая',
  keyLabel: (name: string) => `API Key для ${name}`,
  modelLabel: 'Модель',
  keepKey: 'Оставьте пустым, чтобы сохранить текущий API Key',
  getKey: (name: string) => `Получить API Key на сайте ${name}`,
  saveStart: 'Сохранить и начать',
  test: 'Проверить',
  otherProvider: 'Нет в списке? Настроить другую модель вручную',
  toAdvancedTitle: 'Перейти в расширенный режим?',
  toAdvancedBody: 'Другие сервисы моделей настраиваются на странице «Модель» в расширенном режиме. Вернуться в обычный режим можно внизу слева.',
  testing: 'Проверка…',
  testOk: (ms: number | null) => `Подключение работает${ms !== null ? `, ${ms} мс` : ''}`,
  testFail: (why: string) => `Подключение не удалось: ${why}`,
  started: 'Готово. Coo бодрствует.',
  petTitle: 'Мой настольный питомец',
  petShown: 'На рабочем столе',
  petHidden: 'Скрыт',
  showPet: 'Показать на рабочем столе',
  dress: 'Гардероб',
  guide: 'Обучение',
  guideHint: 'Coo ещё раз всё покажет внизу экрана',
  hidePet: 'Скрыть с рабочего стола',
  connectedLabel: 'Подключённая модель:',
  choicesLabel: 'Доступные модели:',
  notConnected: 'Не подключено',
  schemeTitle: 'Цветовая схема',
};
