import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  nav: 'Accueil',
  modelTitle: 'Connecter un modèle',
  modelNeed: (first: string) => `Choisissez un fournisseur et saisissez son API Key pour commencer. Dans le doute : ${first}.`,
  more: 'Plus',
  toIntl: 'Utiliser la plateforme internationale',
  toCn: 'Utiliser la plateforme de Chine continentale',
  keyLabel: (name: string) => `API Key ${name}`,
  modelLabel: 'Modèle',
  keepKey: 'Laisser vide pour garder la clé enregistrée',
  getKey: (name: string) => `Obtenir une clé ${name}`,
  saveStart: 'Enregistrer et démarrer',
  test: 'Tester',
  otherProvider: 'Introuvable ? Configurer un autre modèle manuellement',
  toAdvancedTitle: 'Passer en mode avancé ?',
  toAdvancedBody: 'Les autres services de modèles se configurent sur la page Modèle du mode avancé. Vous pouvez revenir au mode normal en bas à gauche.',
  testing: 'Test…',
  testOk: (ms: number | null) => `La connexion fonctionne${ms !== null ? `, ${ms} ms` : ''}`,
  testFail: (why: string) => `Échec de la connexion : ${why}`,
  started: "C'est fait. Coo est debout.",
  petTitle: 'Mon compagnon de bureau',
  petShown: 'Sur le bureau',
  petHidden: 'Masqué',
  showPet: 'Afficher sur le bureau',
  dress: 'Habiller',
  guide: 'Guide',
  guideHint: "Coo vous refait la visite en bas de l'écran",
  hidePet: 'Masquer du bureau',
  connectedLabel: 'Modèle connecté :',
  choicesLabel: 'Modèles disponibles :',
  notConnected: 'Non connecté',
};
