import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  nav: 'Inizio',
  modelTitle: 'Collega un modello',
  modelNeed: (first: string) => `Scegli un servizio di modelli e inserisci la sua API Key per iniziare. Nel dubbio, ${first}.`,
  more: 'Altro',
  toIntl: 'Usa la piattaforma internazionale',
  toCn: 'Usa la piattaforma della Cina continentale',
  keyLabel: (name: string) => `API Key di ${name}`,
  modelLabel: 'Modello',
  keepKey: 'Lascia vuoto per mantenere la chiave salvata',
  getKey: (name: string) => `Ottieni una chiave ${name}`,
  saveStart: 'Salva e avvia',
  connected: (model: string, title: string) => `Collegato a ${title} · ${model}`,
  test: 'Prova',
  changeKey: 'Cambia servizio, modello o chiave',
  otherProvider: 'Usa un altro servizio di modelli',
  toAdvancedTitle: 'Passare alla modalità avanzata?',
  toAdvancedBody: 'Gli altri servizi di modelli si configurano nella pagina Modello della modalità avanzata. Puoi tornare alla modalità normale in basso a sinistra.',
  testing: 'Prova in corso…',
  testOk: (ms: number | null) => `La connessione funziona${ms !== null ? `, ${ms} ms` : ''}`,
  testFail: (why: string) => `Connessione non riuscita: ${why}`,
  started: 'Fatto. Coo è in piedi.',
  petTitle: 'Animaletto da desktop',
  petShown: 'Sul desktop',
  petHidden: 'Non visibile',
  showPet: "Mostra l'animaletto",
  dress: 'Guardaroba',
  petNote: "Passa il mouse sull'animaletto per i pulsanti di scrittura e microfono; clic destro per il menu; tieni premuto per sollevare l'animaletto.",
  guide: 'Guida',
  guideHint: 'Coo ti rifà il giro in fondo allo schermo',
};
