import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  nav: 'Inizio',
  modelTitle: 'Collega un modello',
  modelNeed: (first: string) => `Scegli un fornitore e inserisci la sua API Key per iniziare. Nel dubbio, ${first}.`,
  more: 'Altro',
  toIntl: 'Usa la piattaforma internazionale',
  toCn: 'Usa la piattaforma della Cina continentale',
  keyLabel: (name: string) => `API Key di ${name}`,
  modelLabel: 'Modello',
  keepKey: 'Lascia vuoto per mantenere la chiave salvata',
  getKey: (name: string) => `Ottieni una chiave ${name}`,
  saveStart: 'Salva e avvia',
  test: 'Prova',
  otherProvider: 'Non lo trovi? Configura un altro modello manualmente',
  toAdvancedTitle: 'Passare alla modalità avanzata?',
  toAdvancedBody: 'Gli altri servizi di modelli si configurano nella pagina Modello della modalità avanzata. Puoi tornare alla modalità normale in basso a sinistra.',
  testing: 'Prova in corso…',
  testOk: (ms: number | null) => `La connessione funziona${ms !== null ? `, ${ms} ms` : ''}`,
  testFail: (why: string) => `Connessione non riuscita: ${why}`,
  started: 'Fatto. Coo è in piedi.',
  petTitle: 'Il mio animaletto da desktop',
  petShown: 'Sul desktop',
  petHidden: 'Nascosto',
  showPet: 'Mostra sul desktop',
  dress: 'Guardaroba',
  guide: 'Guida',
  guideHint: 'Coo ti rifà il giro in fondo allo schermo',
  hidePet: 'Nascondi dal desktop',
  connectedLabel: 'Modello collegato:',
  choicesLabel: 'Modelli disponibili:',
  notConnected: 'Non collegato',
  schemeTitle: 'Schema di colori della console',
  schemeDesc: 'Si applica subito e viene salvato nella console.',
};
