import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  nav: 'Início',
  title: 'Coo',
  running: 'Acordado',
  paused: 'Pausado',
  noModel: 'Nenhum modelo conectado',
  modelTitle: 'Conectar um modelo',
  modelNeed: (first: string) => `Escolha um serviço de modelos e digite a API Key dele para começar. Na dúvida, ${first}.`,
  more: 'Mais',
  toIntl: 'Usar a plataforma internacional',
  toCn: 'Usar a plataforma da China continental',
  keyLabel: (name: string) => `API Key de ${name}`,
  modelLabel: 'Modelo',
  keepKey: 'Deixe vazio para manter a API Key salva',
  getKey: (name: string) => `Obter uma API Key de ${name}`,
  saveStart: 'Salvar e começar',
  connected: (model: string, title: string) => `Conectado a ${title} · ${model}`,
  test: 'Testar',
  changeKey: 'Trocar serviço, modelo ou API Key',
  otherProvider: 'Usar outro serviço de modelos',
  toAdvancedTitle: 'Mudar para o modo avançado?',
  toAdvancedBody: 'Outros serviços de modelos são configurados na página Modelo do modo avançado. Você pode voltar ao modo normal no canto inferior esquerdo.',
  testing: 'Testando…',
  testOk: (ms: number | null) => `A conexão funciona${ms !== null ? `, ${ms} ms` : ''}`,
  testFail: (why: string) => `Falha na conexão: ${why}`,
  started: 'Pronto. O Coo está acordado.',
  petTitle: 'Pet de área de trabalho',
  petShown: 'Na área de trabalho',
  petHidden: 'Não exibido',
  showPet: 'Mostrar o pet',
  dress: 'Guarda-roupa',
  petNote: 'Passe o mouse sobre o pet para ver os botões de digitar e de microfone; clique com o botão direito para o menu; segure para pegá-lo.',
  guide: 'Guia',
  guideHint: 'O Coo mostra tudo de novo na parte de baixo da tela',
};
