import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  nav: '開始',
  modelTitle: '連線模型',
  modelNeed: (first: string) => `選一家模型服務，填入它的 API Key 就能開始。拿不定主意就選 ${first}。`,
  more: '更多',
  toIntl: '改用國際平台',
  toCn: '改用中國大陸平台',
  keyLabel: (name: string) => `${name} 的 API Key`,
  modelLabel: '模型',
  keepKey: '留空沿用已儲存的 Key',
  getKey: (name: string) => `到 ${name} 申請 Key`,
  saveStart: '儲存並開始',
  connected: (model: string, title: string) => `已連線 ${title} · ${model}`,
  test: '測試連線',
  changeKey: '換一家、換模型或換 Key',
  otherProvider: '使用別的模型服務',
  toAdvancedTitle: '要切換為進階模式嗎？',
  toAdvancedBody: '別的模型服務在進階模式的「模型」頁裡設定。之後可以在左下角切換回一般模式。',
  testing: '正在測試…',
  testOk: (ms: number | null) => `連線正常${ms !== null ? `，耗時 ${ms} ms` : ''}`,
  testFail: (why: string) => `連線失敗：${why}`,
  started: '好了，Coo 醒了。',
  petTitle: '桌寵',
  petShown: '在桌面上',
  petHidden: '沒有顯示',
  showPet: '顯示桌寵',
  dress: '裝扮',
  petNote: '滑鼠停在桌寵身上會出現打字和麥克風兩個按鈕；按右鍵開啟選單；按住可以拎起來。',
  guide: '使用引導',
  guideHint: '讓 Coo 在螢幕底邊再帶你走一遍',
};
