import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  nav: 'Início',
  modelTitle: 'Conectar um modelo',
  modelNeed: (first: string) => `Escolha um provedor e digite a API Key dele para começar. Na dúvida, ${first}.`,
  more: 'Mais',
  toIntl: 'Usar a plataforma internacional',
  toCn: 'Usar a plataforma da China continental',
  keyLabel: (name: string) => `API Key de ${name}`,
  modelLabel: 'Modelo',
  keepKey: 'Deixe vazio para manter a API Key salva',
  getKey: (name: string) => `Obter uma API Key de ${name}`,
  saveStart: 'Salvar e começar',
  test: 'Testar',
  otherProvider: 'Não encontrou? Configure outro modelo manualmente',
  toAdvancedTitle: 'Mudar para o modo avançado?',
  toAdvancedBody: 'Outros serviços de modelos são configurados na página Modelo do modo avançado. Você pode voltar ao modo normal no canto inferior esquerdo.',
  testing: 'Testando…',
  testOk: (ms: number | null) => `A conexão funciona${ms !== null ? `, ${ms} ms` : ''}`,
  testFail: (why: string) => `Falha na conexão: ${why}`,
  started: 'Pronto. Coo acordou.',
  petTitle: 'Meu pet de área de trabalho',
  petShown: 'Na área de trabalho',
  petHidden: 'Oculto',
  showPet: 'Mostrar na área de trabalho',
  dress: 'Guarda-roupa',
  guide: 'Guia',
  guideHint: 'Coo mostra tudo de novo na parte de baixo da tela',
  hidePet: 'Ocultar da área de trabalho',
  connectedLabel: 'Modelo conectado:',
  choicesLabel: 'Modelos disponíveis:',
  notConnected: 'Não conectado',
  schemeTitle: 'Esquema de cores',
};
