import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  nav: 'スタート',
  modelTitle: 'モデルを接続',
  modelNeed: (first: string) => `プロバイダーを選んで API Key を入力すると始められます。迷ったら ${first} を選んでください。`,
  more: 'その他',
  toIntl: '国際版プラットフォームを使う',
  toCn: '中国本土版プラットフォームを使う',
  keyLabel: (name: string) => `${name} の API Key`,
  modelLabel: 'モデル',
  keepKey: '空欄のままなら保存済みの Key を使います',
  getKey: (name: string) => `${name} の Key を取得`,
  saveStart: '保存して開始',
  test: '接続をテスト',
  otherProvider: '見つからない場合は、ほかのモデルを手動で設定',
  toAdvancedTitle: '詳細モードに切り替えますか？',
  toAdvancedBody: 'ほかのモデルサービスは、詳細モードの「モデル」ページで設定します。左下から通常モードに戻せます。',
  testing: 'テストしています…',
  testOk: (ms: number | null) => `接続できました${ms !== null ? `（${ms} ms）` : ''}`,
  testFail: (why: string) => `接続に失敗しました：${why}`,
  started: '完了しました。Coo が起きました。',
  petTitle: 'わたしのデスクトップペット',
  petShown: 'デスクトップに表示中',
  petHidden: '非表示',
  showPet: 'デスクトップに表示',
  dress: '着せ替え',
  guide: 'ガイド',
  guideHint: 'Coo が画面の下でもう一度案内します',
  hidePet: 'デスクトップから隠す',
  connectedLabel: '接続中のモデル：',
  choicesLabel: '選べるモデル：',
  notConnected: '未接続',
};
