import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  nav: 'Start',
  modelTitle: 'Modell verbinden',
  modelNeed: (first: string) => `Wähle einen Modelldienst und gib seinen API Key ein, um loszulegen. Im Zweifel ${first}.`,
  more: 'Mehr',
  toIntl: 'Internationale Plattform verwenden',
  toCn: 'Plattform für Festlandchina verwenden',
  keyLabel: (name: string) => `API Key für ${name}`,
  modelLabel: 'Modell',
  keepKey: 'Leer lassen, um den gespeicherten Schlüssel zu behalten',
  getKey: (name: string) => `Schlüssel für ${name} holen`,
  saveStart: 'Speichern und starten',
  connected: (model: string, title: string) => `Verbunden mit ${title} · ${model}`,
  test: 'Testen',
  changeKey: 'Dienst, Modell oder Schlüssel ändern',
  otherProvider: 'Anderen Modelldienst verwenden',
  toAdvancedTitle: 'Zum erweiterten Modus wechseln?',
  toAdvancedBody: 'Andere Modelldienste richtest du im erweiterten Modus auf der Seite Modell ein. Unten links kannst du zurück zum normalen Modus wechseln.',
  testing: 'Teste…',
  testOk: (ms: number | null) => `Verbindung funktioniert${ms !== null ? `, ${ms} ms` : ''}`,
  testFail: (why: string) => `Verbindung fehlgeschlagen: ${why}`,
  started: 'Fertig. Coo ist wach.',
  petTitle: 'Desktop-Haustier',
  petShown: 'Auf dem Desktop',
  petHidden: 'Nicht angezeigt',
  showPet: 'Haustier anzeigen',
  dress: 'Einkleiden',
  petNote: 'Fahr mit der Maus über das Haustier für die Tipp- und Mikrofon-Schaltflächen; Rechtsklick für das Menü; gedrückt halten, um es hochzuheben.',
  guide: 'Einführung',
  guideHint: 'Coo führt dich unten am Bildschirm noch einmal durch alles',
};
