import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  nav: 'Inicio',
  title: 'Coo',
  running: 'En marcha',
  paused: 'En pausa',
  noModel: 'Sin modelo conectado',
  modelTitle: 'Conectar un modelo',
  modelNeed: (first: string) => `Elige un servicio de modelos e ingresa su API Key para empezar. Si tienes dudas, ${first}.`,
  more: 'Más',
  toIntl: 'Usar la plataforma internacional',
  toCn: 'Usar la plataforma de China continental',
  keyLabel: (name: string) => `API Key de ${name}`,
  modelLabel: 'Modelo',
  keepKey: 'Déjalo vacío para conservar la API Key guardada',
  getKey: (name: string) => `Obtener una API Key de ${name}`,
  saveStart: 'Guardar y empezar',
  connected: (model: string, title: string) => `Conectado a ${title} · ${model}`,
  test: 'Probar',
  changeKey: 'Cambiar servicio, modelo o API Key',
  otherProvider: 'Usar otro servicio de modelos',
  toAdvancedTitle: '¿Cambiar al modo avanzado?',
  toAdvancedBody: 'Los otros servicios de modelos se configuran en la página Modelo del modo avanzado. Puedes volver al modo normal abajo a la izquierda.',
  testing: 'Probando…',
  testOk: (ms: number | null) => `La conexión funciona${ms !== null ? `, ${ms} ms` : ''}`,
  testFail: (why: string) => `Falló la conexión: ${why}`,
  started: 'Listo. Coo ya despertó.',
  petTitle: 'Mascota de escritorio',
  petShown: 'En el escritorio',
  petHidden: 'No se muestra',
  showPet: 'Mostrar mascota',
  dress: 'Vestuario',
  petNote: 'Pasa el cursor sobre la mascota para ver los botones de escribir y de micrófono; clic derecho para el menú; mantén presionado el clic para levantar a Coo.',
  guide: 'Guía',
  guideHint: 'Coo te lo vuelve a mostrar en la parte de abajo de la pantalla',
};
