import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  nav: 'Start',
  modelTitle: 'Modell verbinden',
  modelNeed: (first: string) => `Wähle einen Anbieter und gib seinen API Key ein, um loszulegen. Im Zweifel ${first}.`,
  more: 'Mehr',
  toIntl: 'Internationale Plattform verwenden',
  toCn: 'Plattform für Festlandchina verwenden',
  keyLabel: (name: string) => `API Key für ${name}`,
  modelLabel: 'Modell',
  keepKey: 'Leer lassen, um den gespeicherten Schlüssel zu behalten',
  getKey: (name: string) => `Schlüssel für ${name} holen`,
  saveStart: 'Speichern und starten',
  test: 'Testen',
  otherProvider: 'Nicht dabei? Anderes Modell manuell einrichten',
  toAdvancedTitle: 'Zum erweiterten Modus wechseln?',
  toAdvancedBody: 'Andere Modelldienste richtest du im erweiterten Modus auf der Seite Modell ein. Unten links kannst du zurück zum normalen Modus wechseln.',
  testing: 'Teste…',
  testOk: (ms: number | null) => `Verbindung funktioniert${ms !== null ? `, ${ms} ms` : ''}`,
  testFail: (why: string) => `Verbindung fehlgeschlagen: ${why}`,
  started: 'Fertig. Coo ist wach.',
  petTitle: 'Mein Desktop-Haustier',
  petShown: 'Auf dem Desktop',
  petHidden: 'Ausgeblendet',
  showPet: 'Auf dem Desktop anzeigen',
  dress: 'Einkleiden',
  guide: 'Einführung',
  guideHint: 'Coo führt dich unten am Bildschirm noch einmal durch alles',
  hidePet: 'Vom Desktop ausblenden',
  connectedLabel: 'Verbundenes Modell:',
  choicesLabel: 'Verfügbare Modelle:',
  notConnected: 'Nicht verbunden',
  schemeTitle: 'Farbschema',
};
