import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  nav: 'Inicio',
  modelTitle: 'Conectar un modelo',
  modelNeed: (first: string) => `Elige un proveedor e ingresa su API Key para empezar. Si tienes dudas, ${first}.`,
  more: 'Más',
  toIntl: 'Usar la plataforma internacional',
  toCn: 'Usar la plataforma de China continental',
  keyLabel: (name: string) => `API Key de ${name}`,
  modelLabel: 'Modelo',
  keepKey: 'Déjalo vacío para conservar la API Key guardada',
  getKey: (name: string) => `Obtener una API Key de ${name}`,
  saveStart: 'Guardar y empezar',
  test: 'Probar',
  otherProvider: '¿No aparece? Configura otro modelo manualmente',
  toAdvancedTitle: '¿Cambiar al modo avanzado?',
  toAdvancedBody: 'Los otros servicios de modelos se configuran en la página Modelo del modo avanzado. Puedes volver al modo normal abajo a la izquierda.',
  testing: 'Probando…',
  testOk: (ms: number | null) => `La conexión funciona${ms !== null ? `, ${ms} ms` : ''}`,
  testFail: (why: string) => `Falló la conexión: ${why}`,
  started: 'Listo. Coo ya despertó.',
  petTitle: 'Mi mascota de escritorio',
  petShown: 'En el escritorio',
  petHidden: 'Oculta',
  showPet: 'Mostrar en el escritorio',
  dress: 'Vestuario',
  guide: 'Guía',
  guideHint: 'Coo te lo vuelve a mostrar en la parte de abajo de la pantalla',
  hidePet: 'Ocultar del escritorio',
  connectedLabel: 'Modelo conectado:',
  choicesLabel: 'Modelos disponibles:',
  notConnected: 'Sin conectar',
  schemeTitle: 'Esquema de colores',
};
