import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  nav: 'Accueil',
  title: 'Coo',
  running: 'En éveil',
  paused: 'En pause',
  noModel: 'Aucun modèle connecté',
  modelTitle: 'Connecter un modèle',
  modelNeed: (first: string) => `Choisissez un service de modèles et saisissez son API Key pour commencer. Dans le doute : ${first}.`,
  more: 'Plus',
  toIntl: 'Utiliser la plateforme internationale',
  toCn: 'Utiliser la plateforme de Chine continentale',
  keyLabel: (name: string) => `API Key ${name}`,
  modelLabel: 'Modèle',
  keepKey: 'Laisser vide pour garder la clé enregistrée',
  getKey: (name: string) => `Obtenir une clé ${name}`,
  saveStart: 'Enregistrer et démarrer',
  connected: (model: string, title: string) => `Connecté à ${title} · ${model}`,
  test: 'Tester',
  changeKey: 'Changer de service, de modèle ou de clé',
  otherProvider: 'Utiliser un autre service de modèles',
  toAdvancedTitle: 'Passer en mode avancé ?',
  toAdvancedBody: 'Les autres services de modèles se configurent sur la page Modèle du mode avancé. Vous pouvez revenir au mode normal en bas à gauche.',
  testing: 'Test…',
  testOk: (ms: number | null) => `La connexion fonctionne${ms !== null ? `, ${ms} ms` : ''}`,
  testFail: (why: string) => `Échec de la connexion : ${why}`,
  started: "C'est fait. Coo est debout.",
  petTitle: 'Compagnon de bureau',
  petShown: 'Sur le bureau',
  petHidden: 'Masqué',
  showPet: 'Afficher le compagnon',
  dress: 'Habiller',
  petNote: 'Survolez le compagnon pour les boutons de saisie et de micro ; clic droit pour le menu ; maintenez le clic pour le soulever.',
  guide: 'Guide',
  guideHint: "Coo vous refait la visite en bas de l'écran",
};
