import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  nav: 'Начало',
  title: 'Coo',
  running: 'Бодрствует',
  paused: 'На паузе',
  noModel: 'Модель не подключена',
  modelTitle: 'Подключить модель',
  modelNeed: (first: string) => `Выберите сервис моделей и введите его API Key, чтобы начать. Если не уверены, ${first}.`,
  more: 'Ещё',
  toIntl: 'Использовать международную платформу',
  toCn: 'Использовать платформу для материкового Китая',
  keyLabel: (name: string) => `API Key для ${name}`,
  modelLabel: 'Модель',
  keepKey: 'Оставьте пустым, чтобы сохранить текущий API Key',
  getKey: (name: string) => `Получить API Key на сайте ${name}`,
  saveStart: 'Сохранить и начать',
  connected: (model: string, title: string) => `Подключено: ${title} · ${model}`,
  test: 'Проверить',
  changeKey: 'Сменить сервис, модель или API Key',
  otherProvider: 'Другой сервис моделей',
  toAdvancedTitle: 'Перейти в расширенный режим?',
  toAdvancedBody: 'Другие сервисы моделей настраиваются на странице «Модель» в расширенном режиме. Вернуться в обычный режим можно внизу слева.',
  testing: 'Проверка…',
  testOk: (ms: number | null) => `Подключение работает${ms !== null ? `, ${ms} мс` : ''}`,
  testFail: (why: string) => `Подключение не удалось: ${why}`,
  started: 'Готово. Coo бодрствует.',
  petTitle: 'Настольный питомец',
  petShown: 'На рабочем столе',
  petHidden: 'Скрыт',
  showPet: 'Показать питомца',
  dress: 'Гардероб',
  petNote: 'Наведите курсор на питомца, чтобы появились кнопки ввода текста и микрофона; правая кнопка мыши открывает меню; зажмите питомца, чтобы поднять его.',
  guide: 'Обучение',
  guideHint: 'Coo ещё раз всё покажет внизу экрана',
};
