import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  nav: '시작',
  modelTitle: '모델 연결',
  modelNeed: (first: string) => `공급자를 고르고 API Key를 입력하면 시작할 수 있습니다. 잘 모르겠으면 ${first}을(를) 고르세요.`,
  more: '더 보기',
  toIntl: '국제 플랫폼 사용',
  toCn: '중국 본토 플랫폼 사용',
  keyLabel: (name: string) => `${name} API Key`,
  modelLabel: '모델',
  keepKey: '비워 두면 저장된 Key를 유지합니다',
  getKey: (name: string) => `${name} Key 발급받기`,
  saveStart: '저장하고 시작',
  test: '테스트',
  otherProvider: '찾는 모델이 없나요? 다른 모델 직접 설정',
  toAdvancedTitle: '고급 모드로 전환하시겠습니까?',
  toAdvancedBody: '다른 모델 서비스는 고급 모드의 모델 페이지에서 설정합니다. 왼쪽 아래에서 일반 모드로 다시 전환할 수 있습니다.',
  testing: '테스트하는 중…',
  testOk: (ms: number | null) => `연결 정상${ms !== null ? `, ${ms} ms` : ''}`,
  testFail: (why: string) => `연결 실패: ${why}`,
  started: '완료. Coo가 깨어났습니다.',
  petTitle: '내 데스크톱 펫',
  petShown: '바탕 화면에 표시됨',
  petHidden: '숨김',
  showPet: '바탕 화면에 표시',
  dress: '꾸미기',
  guide: '사용 안내',
  guideHint: 'Coo가 화면 아래쪽에서 처음부터 다시 안내합니다',
  hidePet: '바탕 화면에서 숨기기',
  connectedLabel: '연결된 모델:',
  choicesLabel: '선택할 수 있는 모델:',
  notConnected: '연결되지 않음',
};
