// Generated by node promo/banner.mjs companion assets; uses the banner's existing glyphs.
/** "Coopanion" without the mark, its box centred on the capital height. */
export function coopanionLettering(doc: Document): SVGSVGElement {
  const svg = doc.createElementNS('http://www.w3.org/2000/svg', 'svg');
  svg.setAttribute('viewBox', '-8 18 671.698484809835 148');
  svg.setAttribute('fill', 'none');
  svg.setAttribute('stroke', 'currentColor');
  svg.setAttribute('stroke-width', '16');
  svg.setAttribute('stroke-linecap', 'round');
  svg.setAttribute('stroke-linejoin', 'round');
  svg.setAttribute('aria-hidden', 'true');
  svg.classList.add('wordmark-lettering');
  svg.innerHTML = "<path d=\"M71.7 62.3A42 42 0 1 0 71.7 121.7\"/><path d=\"M126.698484809835 86A24 24 0 1 1 126.698484809835 134A24 24 0 1 1 126.698484809835 86\" class=\"accent\"/><path d=\"M205.698484809835 86A24 24 0 1 1 205.698484809835 134A24 24 0 1 1 205.698484809835 86\" class=\"accent\"/><path d=\"M260.698484809835 86V158\"/><path d=\"M284.698484809835 86A24 24 0 1 1 284.698484809835 134A24 24 0 1 1 284.698484809835 86\"/><path d=\"M363.698484809835 86A24 24 0 1 1 363.698484809835 134A24 24 0 1 1 363.698484809835 86\"/><path d=\"M387.698484809835 86V134\"/><path d=\"M418.698484809835 86V134\"/><path d=\"M418.698484809835 110A24 24 0 0 1 466.698484809835 110V134\"/><path d=\"M497.698484809835 86V134\"/><circle cx=\"497.698484809835\" cy=\"58\" r=\"9\" fill=\"currentColor\" stroke=\"none\"/><path d=\"M552.698484809835 86A24 24 0 1 1 552.698484809835 134A24 24 0 1 1 552.698484809835 86\"/><path d=\"M607.698484809835 86V134\"/><path d=\"M607.698484809835 110A24 24 0 0 1 655.698484809835 110V134\"/>";
  return svg;
}
