import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  nav: '습관',
  language: '언어',
  languageHint: '설정 창과 펫의 말풍선, 메뉴에 이 언어를 쓰며, Coo도 이 언어로 말합니다. 아직 번역되지 않은 부분은 영어로 표시됩니다(중국어 번체는 간체로 표시).',
  user: '부를 이름',
  userHint: 'Coo가 이 이름으로 부릅니다.',
  roam: '걷기',
  roamFree: '자주',
  roamCalm: '가끔',
  roamOff: '제자리',
  theme: '색상',
  themeDark: '야간(밝은 몸)',
  themeLight: '주간(어두운 몸)',
  scale: '크기',
  frameRate: '프레임 레이트',
  frameRateHint: 'Coo가 걷거나, 들려 있거나, 점프할 때 초당 그리는 프레임 수입니다. 디스플레이 주사율보다 높으면 디스플레이 주사율이 적용되며, 무제한은 디스플레이를 따릅니다. 높을수록 CPU와 GPU를 더 씁니다.',
  frameUnlimited: '무제한',
  lockFps: '항상 이 프레임 레이트로 그리기',
  lockFpsHint: '끄면 Coo가 서 있거나, 앉아 있거나, 잠든 동안 초당 30프레임으로 그려 자원을 덜 씁니다. 켜면 가만히 있을 때도 위의 프레임 레이트로 그립니다.',
  hideFullscreen: '전체 화면일 때 숨기기',
  hideFullscreenHint: '게임, 동영상, 브라우저가 화면을 가득 채우는 동안 Coo가 비켜 있다가 전체 화면이 끝나면 돌아옵니다. 최대화된 창은 해당하지 않습니다.',
  soundTitle: '효과음',
  sound: '효과음 재생',
  soundHint: 'Coo 메뉴의 효과음 버튼도 이 설정을 켜고 끕니다.',
  soundKinds: '종류별',
  soundKindsHint: '끈 종류는 소리가 나지 않고 나머지는 그대로 재생됩니다. 항목에 포인터를 올리면 어떤 소리가 포함되는지 볼 수 있습니다. 외형 팩 자체의 소리도 이 종류에 속합니다.',
  kinds: {
    move: ['움직임', '걷기, 달리기, 점프, 착지, 던져지기, 끄덕이기, 고개 젓기, 회전, 어지러움, 떨기, 춤, 두리번거리기'],
    touch: ['터치', '들어 올려지기, 흔들리기, 쓰다듬어지기, 찔리기'],
    face: ['표정', '기쁨, 윙크, 사랑, 놀람, 화남, 슬픔, 부끄러움, 하품'],
    snore: ['코골이', '잠든 동안 코 고는 소리'],
    talk: ['말하기', '말풍선 글자가 나타날 때의 옹알이 소리, 선택 카드가 튀어나오는 소리'],
    ui: ['버튼과 알림음', '버튼 클릭, 말풍선 열림, 선택, 듣기 시작과 끝'],
  },
  snore: '코골이 시간',
  snoreUnit: '초',
  snoreHint: '잠들 때마다 이만큼 코를 곤 뒤 조용해지며, z는 계속 떠오릅니다. 0 = 깰 때까지 코골이.',
  remember: 'Coo 위치 기억',
  rememberHint: '앱을 종료할 때 Coo가 화면 가로 방향 어디에 서 있는지 저장합니다. 화면이 여러 개이면 Coo는 항상 주 화면에서 시작합니다.',
  hover: '호버 버튼',
  hoverHint: (n: number) => `포인터를 Coo 위에 올려 두면 옆에 나타나는 버튼으로, 최대 ${n}개입니다.`,
  dblclick: 'Coo를 더블클릭해 입력 상자 열기',
  statusBubble: 'Coo가 하는 일 표시',
  statusBubbleHint: 'Coo가 생각하거나, 기억 속 파일을 살펴보거나, 컴퓨터를 사용할 때 머리 위 작은 말풍선에 표시합니다. 파일 이름도 표시됩니다.',
  wake: '반응 모드',
  wakeModes: { none: '조용히', poke: '기본', all: '적극적', custom: '사용자 지정…' },
  wakeHints: { none: '상호작용은 기억해 두었다가 말을 걸 때 함께 반응해요', poke: '찌를 때만 반응해요', all: '모든 상호작용에 반응해요' },
  wakeCustomHint: (kinds: string[]) => `${kinds.join(', ')}에는 바로 반응하고, 나머지 상호작용은 말을 걸 때 함께 반응해요`,
  wakeTitle: '바로 반응하는 상호작용',
  wakeKinds: { poke: '찌르기', pet: '머리 쓰다듬기', throw: '던지기', drop: '들었다 내려놓기' },
  self: '스스로 설정 권한',
  selfModes: { off: '금지', default: '기본', any: '모두', custom: '사용자 지정…' },
  selfHints: { off: '설정을 스스로 바꿀 수 없어요', default: '외형, 꾸미기, 걷기, 코골이는 직접 바꾸고, 크기, 효과음, 테마, 호버 버튼, 부를 이름은 먼저 동의를 구해요', any: '모든 설정을 직접 바꿀 수 있어요' },
  selfCustomHint: (direct: string[], asked: string[]) => (direct.length ? `직접 바꿈: ${direct.join(', ')}. 먼저 동의를 구함: ${asked.join(', ')}` : '어떤 설정이든 바꾸기 전에 먼저 동의를 구해요'),
  selfTitle: '직접 바꿀 수 있는 항목',
  selfNote: '체크하지 않은 항목은 바꾸기 전에 먼저 동의를 구해요.',
  selfItems: { figure: '외형', scheme: '꾸미기', roam: '걷기', snoreSeconds: '코골이 길이', sound: '효과음', scale: '크기', theme: '테마', hoverButtons: '호버 버튼', user: '부를 이름' },
  popupSave: '저장',
  popupCancel: '취소',
  actions: { chat: '입력', voice: '음성 입력', roam: '걷기', theme: '야간 모드', sound: '효과음', dress: '꾸미기', hide: '펫 숨기기' },
  saved: '저장됨',
  saveFailed: (why: string) => `저장하지 못했습니다: ${why}`,
  stats: '익명 사용 통계',
  statsHint: '사용 횟수, 사용 시간, 설정을 보내며 대화, Key, 파일은 보내지 않습니다.',
  statsDoc: '보내는 항목 전체',
  groupGeneral: '일반',
  groupBehavior: '행동과 상호작용',
  groupDisplay: '표시',
  statsLabel: '사용 통계',
  dblclickLabel: '더블클릭',
  statusBubbleLabel: '상태 말풍선',
  hideFullscreenLabel: '전체 화면',
  rememberLabel: '위치',
  soundLabel: '효과음',
};
