import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  nav: 'Gewohnheiten',
  language: 'Sprache',
  languageHint: 'Das Einstellungsfenster sowie die Sprechblasen und das Menü des Haustiers verwenden diese Sprache, und Coo spricht in ihr mit dir. Noch nicht übersetzter Text erscheint auf Englisch (traditionelles Chinesisch erscheint vereinfacht).',
  user: 'Wie du genannt wirst',
  userHint: 'Coo nennt dich bei diesem Namen.',
  roam: 'Herumlaufen',
  roamFree: 'Oft',
  roamCalm: 'Ab und zu',
  roamOff: 'Bleibt stehen',
  theme: 'Farben',
  themeDark: 'Nacht (heller Körper)',
  themeLight: 'Tag (dunkler Körper)',
  scale: 'Größe',
  frameRate: 'Bildrate',
  frameRateHint: 'Bilder pro Sekunde, während Coo läuft, getragen wird oder springt. Über der Bildwiederholrate des Bildschirms gilt die des Bildschirms; Unbegrenzt folgt dem Bildschirm. Höhere Raten brauchen mehr CPU und GPU.',
  frameUnlimited: 'Unbegrenzt',
  lockFps: 'Immer mit dieser Rate zeichnen',
  lockFpsHint: 'Aus: Coo zeichnet im Stehen, Sitzen oder Schlafen 30 Bilder pro Sekunde, was weniger verbraucht. An: die Rate oben auch im Ruhezustand.',
  hideFullscreen: 'Bei Vollbild ausblenden',
  hideFullscreenHint: 'Coo tritt beiseite, solange ein Spiel, ein Video oder ein Browser seinen Bildschirm füllt, und kommt zurück, wenn das Vollbild endet. Ein maximiertes Fenster zählt nicht.',
  soundTitle: 'Töne',
  sound: 'Töne abspielen',
  soundHint: 'Die Ton-Schaltfläche in Coos Menü schaltet das ebenfalls um.',
  soundKinds: 'Nach Art',
  soundKindsHint: 'Eine ausgeschaltete Art bleibt stumm; der Rest spielt wie gewohnt. Bleib mit dem Mauszeiger auf einer Art, um zu sehen, welche Töne dazugehören. Die eigenen Töne eines Figurenpakets fallen auch unter diese Arten.',
  kinds: {
    move: ['Bewegung', 'Gehen, Rennen, Springen, Landen, Geworfenwerden, Nicken, Kopfschütteln, Drehen, Schwindel, Zittern, Tanzen, Umherschauen'],
    touch: ['Berührung', 'Hochgehoben, geschwungen, gestreichelt, angestupst werden'],
    face: ['Gesichter', 'Fröhlich, Zwinkern, Liebe, überrascht, wütend, traurig, schüchtern, Gähnen'],
    snore: ['Schnarchen', 'Schnarcht im Schlaf'],
    talk: ['Sprechen', 'Das Geplapper, während Sprechblasentext erscheint, aufpoppende Auswahlkarten'],
    ui: ['Schaltflächen und Signale', 'Schaltflächenklicks, sich öffnende Sprechblasen, Auswahlen, Beginn und Ende des Zuhörens'],
  },
  snore: 'Schnarchen für',
  snoreUnit: 's',
  snoreHint: 'In jedem Schlaf wird Coo nach so langem Schnarchen still; die Zs schweben weiter. 0 = schnarchen bis zum Aufwachen.',
  remember: 'Merken, wo Coo steht',
  rememberHint: 'Speichert beim Beenden der App, wie weit links oder rechts Coo auf dem Bildschirm steht; bei mehreren Bildschirmen startet Coo immer auf dem Hauptbildschirm.',
  hover: 'Hover-Schaltflächen',
  hoverHint: (n: number) => `Schaltflächen neben Coo, solange der Mauszeiger darauf ruht, bis zu ${n}.`,
  dblclick: 'Doppelklick auf Coo öffnet das Eingabefeld',
  statusBubble: 'Zeigen, was Coo gerade tut',
  statusBubbleHint: 'Eine kleine Blase über Coo zeigt, wenn es nachdenkt, Dateien in seinem Gedächtnis durchsieht oder den Computer bedient. Dateinamen werden angezeigt.',
  wake: 'Reaktionsmodus',
  wakeModes: { none: 'Ruhig', poke: 'Standard', all: 'Aktiv', custom: 'Eigene…' },
  wakeHints: { none: 'Berührungen werden gemerkt und gesammelt beantwortet, wenn du das nächste Mal etwas sagst', poke: 'Reagiert nur, wenn du Coo anstupst', all: 'Reagiert auf jede Berührung' },
  wakeCustomHint: (kinds: string[]) => `Reagiert sofort auf: ${kinds.join(', ')}. Andere Berührungen werden gesammelt beantwortet, wenn du das nächste Mal etwas sagst`,
  wakeTitle: 'Auf diese Berührungen kommt sofort eine Reaktion',
  wakeKinds: { poke: 'Anstupsen', pet: 'Kopf streicheln', throw: 'Werfen', drop: 'Hochheben und absetzen' },
  self: 'Selbsteinstellung',
  selfModes: { off: 'Verboten', default: 'Standard', any: 'Alles', custom: 'Eigene…' },
  selfHints: { off: 'Kann Einstellungen nicht selbst ändern', default: 'Figur, Outfit, Herumlaufen und Schnarchen werden direkt geändert; bei Größe, Tönen, Design, Hover-Schaltflächen und deinem Namen wird erst deine Zustimmung eingeholt', any: 'Alle Einstellungen können direkt geändert werden' },
  selfCustomHint: (direct: string[], asked: string[]) => (direct.length ? `Direkt geändert: ${direct.join(', ')}. Erst mit deiner Zustimmung: ${asked.join(', ')}` : 'Jede Einstellung wird erst nach deiner Zustimmung geändert'),
  selfTitle: 'Direkt änderbare Einstellungen',
  selfNote: 'Was nicht angehakt ist, wird erst nach deiner Zustimmung geändert.',
  selfItems: { figure: 'Figur', scheme: 'Outfit', roam: 'Herumlaufen', snoreSeconds: 'Schnarchdauer', sound: 'Töne', scale: 'Größe', theme: 'Design', hoverButtons: 'Hover-Schaltflächen', user: 'Wie du genannt wirst' },
  popupSave: 'Speichern',
  popupCancel: 'Abbrechen',
  actions: { chat: 'Tippen', voice: 'Spracheingabe', roam: 'Herumlaufen', theme: 'Nachtmodus', sound: 'Töne', dress: 'Outfit', hide: 'Haustier ausblenden' },
  saved: 'Gespeichert',
  saveFailed: (why: string) => `Nicht gespeichert: ${why}`,
  stats: 'Anonyme Nutzungsstatistik',
  statsHint: 'Sendet Zähler, Nutzungsdauer und Einstellungen; nie Unterhaltungen, Schlüssel oder Dateien.',
  statsDoc: 'Alle gesendeten Felder',
  groupGeneral: 'Allgemein',
  groupBehavior: 'Verhalten',
  groupDisplay: 'Anzeige',
  statsLabel: 'Nutzungsstatistik',
  dblclickLabel: 'Doppelklick',
  statusBubbleLabel: 'Statusblase',
  hideFullscreenLabel: 'Vollbild',
  rememberLabel: 'Position',
  soundLabel: 'Töne',
};
