import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  nav: 'Gewohnheiten',
  settingsTitle: 'Gewohnheiten',
  language: 'Sprache',
  languageHint: 'Das Einstellungsfenster sowie die Sprechblasen und das Menü des Haustiers verwenden diese Sprache, und Coo spricht in ihr mit dir. Noch nicht übersetzter Text erscheint auf Englisch (traditionelles Chinesisch erscheint vereinfacht).',
  user: 'Wie du genannt wirst',
  userHint: 'Coo nennt dich bei diesem Namen.',
  roam: 'Herumlaufen',
  roamFree: 'Oft',
  roamCalm: 'Ab und zu',
  roamOff: 'Bleibt stehen',
  theme: 'Farben',
  themeDark: 'Nacht (heller Körper)',
  themeLight: 'Tag (dunkler Körper)',
  scale: 'Größe',
  frameRate: 'Bildrate',
  frameRateHint: 'Bilder pro Sekunde, während Coo läuft, getragen wird oder springt. Über der Bildwiederholrate des Bildschirms gilt die des Bildschirms; Unbegrenzt folgt dem Bildschirm. Höhere Raten brauchen mehr CPU und GPU.',
  frameUnlimited: 'Unbegrenzt',
  lockFps: 'Immer mit dieser Rate zeichnen',
  lockFpsHint: 'Aus: Coo zeichnet im Stehen, Sitzen oder Schlafen 30 Bilder pro Sekunde, was weniger verbraucht. An: die Rate oben auch im Ruhezustand.',
  hideFullscreen: 'Bei Vollbild ausblenden',
  hideFullscreenHint: 'Coo tritt beiseite, solange ein Spiel, ein Video oder ein Browser seinen Bildschirm füllt, und kommt zurück, wenn das Vollbild endet. Ein maximiertes Fenster zählt nicht.',
  soundTitle: 'Töne',
  sound: 'Töne abspielen',
  soundHint: 'Die Ton-Schaltfläche in Coos Menü schaltet das ebenfalls um.',
  soundKinds: 'Nach Art',
  soundKindsHint: 'Eine ausgeschaltete Art bleibt stumm; der Rest spielt wie gewohnt. Bleib mit dem Mauszeiger auf einer Art, um zu sehen, welche Töne dazugehören. Die eigenen Töne eines Figurenpakets fallen auch unter diese Arten.',
  kinds: {
    move: ['Bewegung', 'Gehen, Rennen, Springen, Landen, Geworfenwerden, Nicken, Kopfschütteln, Drehen, Schwindel, Zittern, Tanzen, Umherschauen'],
    touch: ['Berührung', 'Hochgehoben, geschwungen, gestreichelt, angestupst werden'],
    face: ['Gesichter', 'Fröhlich, Zwinkern, Liebe, überrascht, wütend, traurig, schüchtern, Gähnen'],
    snore: ['Schnarchen', 'Schnarcht im Schlaf'],
    talk: ['Sprechen', 'Das Geplapper, während Sprechblasentext erscheint, aufpoppende Auswahlkarten'],
    ui: ['Schaltflächen und Signale', 'Schaltflächenklicks, sich öffnende Sprechblasen, Auswahlen, Beginn und Ende des Zuhörens'],
  },
  snore: 'Schnarchen für',
  snoreUnit: 's',
  snoreHint: 'In jedem Schlaf wird Coo nach so langem Schnarchen still; die Zs schweben weiter. 0 = schnarchen bis zum Aufwachen.',
  remember: 'Merken, wo Coo steht',
  rememberHint: 'Speichert beim Beenden der App, wie weit links oder rechts Coo auf dem Bildschirm steht; bei mehreren Bildschirmen startet Coo immer auf dem Hauptbildschirm.',
  hover: 'Hover-Schaltflächen',
  hoverHint: (n: number) => `Schaltflächen neben Coo, solange der Mauszeiger darauf ruht, bis zu ${n}.`,
  dblclick: 'Doppelklick auf Coo öffnet das Eingabefeld',
  statusBubble: 'Zeigen, was Coo gerade tut',
  statusBubbleHint: 'Eine kleine Blase über Coo zeigt, wenn es nachdenkt, Dateien in seinem Gedächtnis durchsieht oder den Computer bedient. Dateinamen werden angezeigt.',
  wake: 'Reaktionsmodus',
  wakeModes: { none: 'Ruhig', poke: 'Standard', all: 'Aktiv', custom: 'Eigene…' },
  wakeHints: { none: 'Berührungen werden gemerkt und beantwortet, wenn du Coo das nächste Mal ansprichst', poke: 'Reagiert nur, wenn du Coo anstupst', all: 'Reagiert auf jede Berührung' },
  wakeCustomHint: (kinds: string[]) => `Reagiert sofort auf: ${kinds.join(', ')}. Andere Berührungen warten, bis du Coo ansprichst`,
  wakeTitle: 'Auf diese Berührungen reagiert Coo sofort',
  wakeKinds: { poke: 'Anstupsen', pet: 'Kopf streicheln', throw: 'Werfen', drop: 'Hochheben und absetzen' },
  self: 'Selbsteinstellung',
  selfModes: { off: 'Verboten', default: 'Standard', any: 'Alles', custom: 'Eigene…' },
  selfHints: { off: 'Coo kann seine Einstellungen nicht selbst ändern', default: 'Figur, Outfit, Herumlaufen und Schnarchen ändert Coo direkt; bei Größe, Tönen, Design, Hover-Schaltflächen und deinem Namen holt es erst deine Zustimmung ein', any: 'Coo kann alle Einstellungen direkt ändern' },
  selfCustomHint: (direct: string[], asked: string[]) => (direct.length ? `Ändert direkt: ${direct.join(', ')}. Holt erst deine Zustimmung ein: ${asked.join(', ')}` : 'Coo holt vor jeder Änderung deine Zustimmung ein'),
  selfTitle: 'Das darf Coo direkt ändern',
  selfNote: 'Bei allem, was nicht angehakt ist, holt Coo vorher deine Zustimmung ein.',
  selfItems: { figure: 'Figur', scheme: 'Outfit', roam: 'Herumlaufen', snoreSeconds: 'Schnarchdauer', sound: 'Töne', scale: 'Größe', theme: 'Design', hoverButtons: 'Hover-Schaltflächen', user: 'Wie du genannt wirst' },
  popupSave: 'Speichern',
  popupCancel: 'Abbrechen',
  actions: { chat: 'Tippen', voice: 'Spracheingabe', roam: 'Herumlaufen', theme: 'Nachtmodus', sound: 'Töne', dress: 'Outfit', hide: 'Haustier ausblenden' },
  saved: 'Gespeichert',
  saveFailed: (why: string) => `Nicht gespeichert: ${why}`,
  stats: 'Anonyme Nutzungsstatistik',
  statsHint: 'Sendet Zähler, Nutzungsdauer und Einstellungen; nie Unterhaltungen, Schlüssel oder Dateien.',
  statsDoc: 'Alle gesendeten Felder',
};
