import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  nav: 'Hábitos',
  settingsTitle: 'Hábitos',
  language: 'Idioma',
  languageHint: 'A janela de configurações e os balões e o menu do pet usam este idioma, e Coo fala com você nele. Textos ainda não traduzidos aparecem em inglês (o chinês tradicional mostra o simplificado).',
  user: 'Como chamar você',
  userHint: 'Coo chama você por este nome.',
  roam: 'Passeios',
  roamFree: 'Com frequência',
  roamCalm: 'De vez em quando',
  roamOff: 'Sem se mexer',
  theme: 'Cores',
  themeDark: 'Noite (corpo claro)',
  themeLight: 'Dia (corpo escuro)',
  scale: 'Tamanho',
  frameRate: 'Taxa de quadros',
  frameRateHint: 'Quadros por segundo enquanto Coo anda ou pula, ou enquanto você carrega Coo. Acima da taxa de atualização da tela, vale a da tela; Sem limite segue a tela. Taxas mais altas usam mais CPU e GPU.',
  frameUnlimited: 'Sem limite',
  lockFps: 'Sempre desenhar nesta taxa',
  lockFpsHint: 'Desligado: Coo desenha 30 quadros por segundo quando está em pé, na posição sentada ou dormindo, o que gasta menos. Ligado: a taxa acima também em repouso.',
  hideFullscreen: 'Ocultar em tela cheia',
  hideFullscreenHint: 'Coo sai de cena enquanto um jogo, um vídeo ou um navegador ocupa a tela de Coo, e volta quando a tela cheia termina. Uma janela maximizada não conta.',
  soundTitle: 'Sons',
  sound: 'Tocar sons',
  soundHint: 'O botão de som no menu de Coo também alterna isto.',
  soundKinds: 'Por tipo',
  soundKindsHint: 'Um tipo desligado fica mudo; os demais tocam normalmente. Deixe o ponteiro sobre um para ver quais sons ele inclui. Os sons próprios de um pacote de personagem também entram nesses tipos.',
  kinds: {
    move: ['Movimentos', 'Andar, correr, pular, aterrissar, arremesso, acenar com a cabeça, balançar a cabeça, girar, tontura, tremer, dançar, olhar em volta'],
    touch: ['Toque', 'Pegar, balançar, fazer carinho, cutucar'],
    face: ['Expressões', 'Feliz, piscadela, amor, surpresa, raiva, tristeza, timidez, bocejo'],
    snore: ['Ronco', 'Roncos durante o sono'],
    talk: ['Fala', 'O balbucio enquanto o texto do balão aparece, cartões de opção surgindo'],
    ui: ['Botões e avisos', 'Cliques em botões, balões abrindo, seleções, início e fim da escuta'],
  },
  snore: 'Roncar por',
  snoreUnit: 's',
  snoreHint: 'Em cada soneca, Coo para de roncar depois desse tempo; os z continuam flutuando. 0 = roncar até acordar.',
  remember: 'Lembrar onde Coo fica',
  rememberHint: 'Salva em que ponto horizontal da tela Coo está quando o app fecha; com várias telas, Coo sempre começa na principal.',
  hover: 'Botões ao passar o mouse',
  hoverHint: (n: number) => `Botões ao lado de Coo enquanto o ponteiro está em cima, até ${n}.`,
  dblclick: 'Clique duplo em Coo para abrir a caixa de texto',
  statusBubble: 'Mostrar o que Coo está fazendo',
  statusBubbleHint: 'Um balãozinho acima de Coo mostra quando está pensando, consultando arquivos da memória ou usando o computador. Os nomes dos arquivos aparecem.',
  wake: 'Modo de resposta',
  wakeModes: { none: 'Quieto', poke: 'Padrão', all: 'Ativo', custom: 'Personalizado…' },
  wakeHints: { none: 'Os toques ficam anotados e são respondidos juntos quando você falar', poke: 'Só responde quando você cutuca', all: 'Responde a todos os toques' },
  wakeCustomHint: (kinds: string[]) => `Responde na hora a: ${kinds.join(', ')}. Os outros toques são respondidos juntos quando você falar`,
  wakeTitle: 'Estes toques têm resposta na hora',
  wakeKinds: { poke: 'Cutucar', pet: 'Carinho na cabeça', throw: 'Arremessar', drop: 'Levantar e soltar' },
  self: 'Autoajuste',
  selfModes: { off: 'Proibido', default: 'Padrão', any: 'Tudo', custom: 'Personalizado…' },
  selfHints: { off: 'Não pode mudar as configurações por conta própria', default: 'Personagem, visual, passeios e ronco mudam direto; tamanho, sons, tema, botões ao passar o mouse e como chamar você só mudam com seu consentimento', any: 'Todas as configurações podem mudar direto' },
  selfCustomHint: (direct: string[], asked: string[]) => (direct.length ? `Mudam direto: ${direct.join(', ')}. Só mudam com seu consentimento: ${asked.join(', ')}` : 'Toda configuração só muda com seu consentimento'),
  selfTitle: 'Itens que podem mudar direto',
  selfNote: 'Os itens não marcados só mudam com seu consentimento.',
  selfItems: { figure: 'Personagem', scheme: 'Visual', roam: 'Passeios', snoreSeconds: 'Duração do ronco', sound: 'Sons', scale: 'Tamanho', theme: 'Tema', hoverButtons: 'Botões ao passar o mouse', user: 'Como chamar você' },
  popupSave: 'Salvar',
  popupCancel: 'Cancelar',
  actions: { chat: 'Digitar', voice: 'Entrada de voz', roam: 'Passeios', theme: 'Modo noturno', sound: 'Sons', dress: 'Guarda-roupa', hide: 'Ocultar o pet' },
  saved: 'Salvo',
  saveFailed: (why: string) => `Não foi salvo: ${why}`,
  stats: 'Estatísticas de uso anônimas',
  statsHint: 'Envia contagens, tempo de uso e configurações; nunca conversas, API Keys ou arquivos.',
  statsDoc: 'Todos os campos enviados',
};
