import { pick } from '../../core/language.ts';
import { S as zhHant } from './strings.zh-Hant.ts';
import { S as ja } from './strings.ja.ts';
import { S as ko } from './strings.ko.ts';
import { S as fr } from './strings.fr.ts';
import { S as de } from './strings.de.ts';
import { S as es419 } from './strings.es-419.ts';
import { S as ptBR } from './strings.pt-BR.ts';
import { S as it } from './strings.it.ts';
import { S as ru } from './strings.ru.ts';

const zh = {
  nav: '习惯',
  settingsTitle: '习惯',
  language: '语言',
  languageHint: '设置窗口、桌宠的气泡和菜单都用这种语言，Coo 也用它和你说话。还没有译文的地方显示英文（繁体中文显示简体）。',
  user: '怎么称呼你',
  userHint: 'Coo 会用这个名字叫你。',
  roam: '走动',
  roamFree: '常走动',
  roamCalm: '多待着',
  roamOff: '不乱动',
  theme: '颜色',
  themeDark: '夜间（浅色身体）',
  themeLight: '白天（深色身体）',
  scale: '大小',
  frameRate: '帧率',
  frameRateHint: '走动、被拎着、跳起时每秒画多少帧。超过显示器刷新率时按显示器的；「不限」就是跟随显示器刷新率。帧率越高越费 CPU 和显卡。',
  frameUnlimited: '不限',
  lockFps: '一直按这个帧率画',
  lockFpsHint: '关着时 Coo 站着、坐着、睡着每秒画 30 帧，占用更少；打开后静止时也按上面的帧率画。',
  hideFullscreen: '全屏时自动隐藏',
  hideFullscreenHint: '玩游戏、看全屏视频、浏览器全屏时 Coo 先躲起来，退出全屏再出来。最大化的窗口不算全屏。',
  soundTitle: '音效',
  sound: '播放音效',
  soundHint: 'Coo 菜单中的音效按钮控制同一项设置。',
  soundKinds: '分别开关',
  soundKindsHint: '关掉的那类不再出声，其余照常。鼠标停在一项上能看到它包括哪些声音。形象包自带的声音也归在这几类里。',
  kinds: {
    move: ['动作', '走路、跑、跳、落地、被甩出去、点头、摇头、转圈、晕、发抖、跳舞、张望'],
    touch: ['互动', '被拎起来、拎着晃、被摸、被戳'],
    face: ['表情', '开心、眨眼、喜欢、惊讶、生气、难过、害羞、打哈欠'],
    snore: ['打呼噜', '睡着时的呼噜声'],
    talk: ['说话', '气泡里逐字冒出的叽咕声、选项卡片弹出'],
    ui: ['按钮与提示', '点按钮、气泡弹出、选中、开始和结束听你说话'],
  } as Record<string, [string, string]>,
  snore: '呼噜打多久',
  snoreUnit: '秒',
  snoreHint: '每次睡着后打这么久呼噜就安静下来，Z 照样飘。0 = 一直打到醒。',
  remember: '记住位置',
  rememberHint: '退出时记下 Coo 的横向位置，下次启动回到那里；有多块屏幕时总在主屏上启动。',
  hover: '悬停按钮',
  hoverHint: (n: number) => `鼠标停在 Coo 身上时旁边出现的按钮，最多 ${n} 个。`,
  dblclick: '双击 Coo 打开打字框',
  statusBubble: '显示 Coo 在忙什么',
  statusBubbleHint: 'Coo 想事情、翻记忆里的文件、操作电脑时，头顶冒个小泡写着在做什么，会显示文件名。',
  wake: '回应模式',
  wakeModes: { none: '安静', poke: '默认', all: '积极', custom: '自定义…' } as Record<string, string>,
  wakeHints: { none: '互动先记着，等你说话时一起回应', poke: '只有被戳的时候才回应', all: '所有互动都会回应' } as Record<string, string>,
  wakeCustomHint: (kinds: string[]) => `${kinds.join('、')}时马上回应，其余互动等你说话时一起回应`,
  wakeTitle: '这些互动会马上得到回应',
  wakeKinds: { poke: '戳一下', pet: '摸头', throw: '甩出去', drop: '拎起来放下' } as Record<string, string>,
  self: '自主配置权限',
  selfModes: { off: '禁止', default: '默认', any: '任意', custom: '自定义…' } as Record<string, string>,
  selfHints: { off: '不能自己改设置', default: '形象、配色、走动和打呼直接改；大小、音效、主题、悬停按钮和称呼会先征得你同意', any: '所有设置都可以直接改' } as Record<string, string>,
  selfCustomHint: (direct: string[], asked: string[]) => (direct.length ? `${direct.join('、')}直接改；${asked.join('、')}会先征得你同意` : '每项设置都会先征得你同意再改'),
  selfTitle: '可以直接改的项',
  selfNote: '没勾的项，改之前会先征得你同意。',
  selfItems: { figure: '形象', scheme: '配色', roam: '走动', snoreSeconds: '打呼间隔', sound: '音效', scale: '大小', theme: '主题', hoverButtons: '悬停按钮', user: '称呼' } as Record<string, string>,
  popupSave: '保存',
  popupCancel: '取消',
  actions: { chat: '打字', voice: '语音输入', roam: '行为模式', theme: '夜间模式', sound: '音效', dress: '装扮', hide: '隐藏桌宠' } as Record<string, string>,
  saved: '已保存',
  saveFailed: (why: string) => `保存失败：${why}`,
  stats: '匿名使用统计',
  statsHint: '发送使用次数、时长和设置，不含对话内容、Key 和文件。',
  statsDoc: '具体发送哪些字段',
};

export const en: typeof zh = {
  nav: 'Habits',
  settingsTitle: 'Habits',
  language: 'Language',
  languageHint: 'The settings window and the pet\'s bubbles and menu use this language, and Coo talks to you in it. Text not yet translated shows in English (Traditional Chinese shows Simplified).',
  user: 'What to call you',
  userHint: 'Coo calls you by this name.',
  roam: 'Walking',
  roamFree: 'Often',
  roamCalm: 'Now and then',
  roamOff: 'Stay put',
  theme: 'Colors',
  themeDark: 'Night (light body)',
  themeLight: 'Day (dark body)',
  scale: 'Size',
  frameRate: 'Frame rate',
  frameRateHint: 'Frames a second while Coo walks, is carried or jumps. Above the display\'s refresh rate the display\'s rate applies; Unlimited follows the display. Higher rates use more CPU and GPU.',
  frameUnlimited: 'Unlimited',
  lockFps: 'Always draw at this rate',
  lockFpsHint: 'Off: Coo draws 30 frames a second while standing, sitting or asleep, which uses less. On: the rate above at rest too.',
  hideFullscreen: 'Hide during full screen',
  hideFullscreenHint: 'Coo steps away while a game, a video or a browser fills its screen, and comes back when full screen ends. A maximized window does not count.',
  soundTitle: 'Sounds',
  sound: 'Play sounds',
  soundHint: "The sound button in Coo's menu controls the same setting.",
  soundKinds: 'By kind',
  soundKindsHint: "A kind switched off stays silent; the rest play as usual. Rest the pointer on one to see which sounds it covers. A figure pack's own sounds fall under these kinds too.",
  kinds: {
    move: ['Moving', 'Walking, running, jumping, landing, being thrown, nodding, shaking, spinning, dizziness, shivering, dancing, looking about'],
    touch: ['Touch', 'Being picked up, swung, petted, poked'],
    face: ['Faces', 'Happy, wink, love, surprised, angry, sad, shy, yawning'],
    snore: ['Snoring', 'Snores while asleep'],
    talk: ['Talking', 'The babble as bubble text appears, choice cards popping up'],
    ui: ['Buttons and cues', 'Button clicks, bubbles opening, picks, listening starting and ending'],
  } as Record<string, [string, string]>,
  snore: 'Snore for',
  snoreUnit: 's',
  snoreHint: "In each sleep Coo goes quiet after snoring this long; the z's keep floating. 0 = snore until waking.",
  remember: 'Remember where Coo stands',
  rememberHint: 'Saves how far across the screen Coo stands when the app quits; with several screens Coo always starts on the main one.',
  hover: 'Hover buttons',
  hoverHint: (n: number) => `Buttons beside Coo while the pointer rests on it, up to ${n}.`,
  dblclick: 'Double-click Coo to open the typing box',
  statusBubble: 'Show what Coo is doing',
  statusBubbleHint: 'A small bubble above Coo shows when it is thinking, looking through files in its memory or using the computer. File names are shown.',
  wake: 'Response mode',
  wakeModes: { none: 'Quiet', poke: 'Default', all: 'Eager', custom: 'Custom…' },
  wakeHints: { none: 'Touches are noted and answered together when you next speak', poke: 'Responds only when poked', all: 'Responds to every touch' },
  wakeCustomHint: (kinds: string[]) => `Responds right away to: ${kinds.join(', ')}. Other touches are answered together when you next speak`,
  wakeTitle: 'These touches get a response right away',
  wakeKinds: { poke: 'Poke', pet: 'Pat on the head', throw: 'Throw', drop: 'Pick up and put down' },
  self: 'Self-adjustment',
  selfModes: { off: 'Off', default: 'Default', any: 'Anything', custom: 'Custom…' },
  selfHints: { off: "Can't change any settings", default: 'Figure, dress, walking and snoring change directly; size, sounds, theme, hover buttons and what you are called need your consent first', any: 'Every setting can change directly' },
  selfCustomHint: (direct: string[], asked: string[]) => (direct.length ? `Changes directly: ${direct.join(', ')}. Needs your consent first: ${asked.join(', ')}` : 'Every setting needs your consent before it changes'),
  selfTitle: 'Settings that can change directly',
  selfNote: 'Anything unchecked needs your consent before it changes.',
  selfItems: { figure: 'Figure', scheme: 'Dress', roam: 'Walking', snoreSeconds: 'Snore length', sound: 'Sounds', scale: 'Size', theme: 'Theme', hoverButtons: 'Hover buttons', user: 'What to call you' },
  popupSave: 'Save',
  popupCancel: 'Cancel',
  actions: { chat: 'Type', voice: 'Voice input', roam: 'Walking', theme: 'Night mode', sound: 'Sounds', dress: 'Dress up', hide: 'Hide pet' } as Record<string, string>,
  saved: 'Saved',
  saveFailed: (why: string) => `Not saved: ${why}`,
  stats: 'Anonymous usage statistics',
  statsHint: 'Sends counts, time used and settings; never conversations, keys or files.',
  statsDoc: 'Every field it sends',
};

export const S = pick({
  zh, en, 'zh-Hant': zhHant, ja, ko, fr, de, 'es-419': es419, 'pt-BR': ptBR, it, ru,
});
