import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  nav: 'ふるまい',
  settingsTitle: 'ふるまい',
  language: '言語',
  languageHint: '設定ウィンドウ、ペットの吹き出しとメニューがこの言語で表示され、Coo もこの言語で話します。まだ翻訳されていない文字列は英語で表示されます（繁体字中国語では簡体字で表示されます）。',
  user: 'あなたの呼び名',
  userHint: 'Coo はこの名前であなたを呼びます。',
  roam: '歩き回り',
  roamFree: 'よく歩く',
  roamCalm: 'ときどき歩く',
  roamOff: 'じっとする',
  theme: '色',
  themeDark: '夜（明るい体）',
  themeLight: '昼（暗い体）',
  scale: 'サイズ',
  frameRate: 'フレームレート',
  frameRateHint: 'Coo が歩く、運ばれる、ジャンプするときの 1 秒あたりのフレーム数です。ディスプレイのリフレッシュレートを超える分はディスプレイのレートになり、「無制限」はディスプレイに合わせます。高いほど CPU と GPU を多く使います。',
  frameUnlimited: '無制限',
  lockFps: '常にこのレートで描画',
  lockFpsHint: 'オフ：立っている、座っている、眠っているあいだは 1 秒 30 フレームで描画し、負荷を抑えます。オン：静止中も上のレートで描画します。',
  hideFullscreen: '全画面表示中は隠れる',
  hideFullscreenHint: 'ゲーム、動画、ブラウザーが Coo のいる画面いっぱいに表示されているあいだは隠れ、全画面表示が終わると戻ってきます。最大化したウィンドウは対象外です。',
  soundTitle: 'サウンド',
  sound: 'サウンドを鳴らす',
  soundHint: 'Coo のメニューのサウンドボタンでも切り替えられます。',
  soundKinds: '種類ごと',
  soundKindsHint: 'オフにした種類は鳴らず、ほかはいつもどおり鳴ります。ポインターを乗せると、その種類に含まれる音が表示されます。アバターパック独自の音もこれらの種類に分類されます。',
  kinds: {
    move: ['動き', '歩く、走る、跳ぶ、着地、投げられる、うなずく、首を振る、回る、目を回す、震える、踊る、見回す'],
    touch: ['ふれあい', '持ち上げられる、振り回される、なでられる、つつかれる'],
    face: ['表情', 'うれしい、ウインク、ハート、驚き、怒り、悲しい、照れ、あくび'],
    snore: ['いびき', '眠っているときのいびき'],
    talk: ['おしゃべり', '吹き出しの文字が出るときのおしゃべり音、選択カードが出る音'],
    ui: ['ボタンと合図', 'ボタンのクリック、吹き出しが開く音、選択、聞き取りの開始と終了'],
  },
  snore: 'いびきの長さ',
  snoreUnit: '秒',
  snoreHint: '眠るたびに、この時間いびきをかいたあと静かになります。z の文字は浮かび続けます。0 = 起きるまでいびきをかく。',
  remember: 'Coo の位置を覚える',
  rememberHint: 'アプリの終了時に、Coo が画面の横方向のどこにいたかを保存します。画面が複数あるときは、常にメイン画面で起動します。',
  hover: 'ホバーボタン',
  hoverHint: (n: number) => `ポインターを乗せたときに Coo の横に出るボタン。最大 ${n} 個。`,
  dblclick: 'Coo をダブルクリックで入力欄を開く',
  statusBubble: 'Coo の作業内容を表示',
  statusBubbleHint: '考えているとき、記憶のファイルを見ているとき、コンピューターを操作しているときに、Coo の上に小さな吹き出しが出ます。ファイル名も表示されます。',
  wake: '反応モード',
  wakeModes: { none: '静か', poke: '標準', all: '積極的', custom: 'カスタム…' },
  wakeHints: { none: 'ふれあいは覚えておき、話しかけたときにまとめて反応します', poke: 'つつかれたときだけ反応します', all: 'すべてのふれあいに反応します' },
  wakeCustomHint: (kinds: string[]) => `${kinds.join('、')}にはすぐ反応し、ほかのふれあいは話しかけたときにまとめて反応します`,
  wakeTitle: 'すぐに反応するふれあい',
  wakeKinds: { poke: 'つつく', pet: '頭をなでる', throw: '投げる', drop: '持ち上げて置く' },
  self: '自分で設定する権限',
  selfModes: { off: '禁止', default: '標準', any: 'すべて', custom: 'カスタム…' },
  selfHints: { off: '設定を自分では変えられません', default: 'アバター、着せ替え、歩き回り、いびきは自分で変えます。サイズ、サウンド、テーマ、ホバーボタン、呼び名は先にあなたの同意を得ます', any: 'すべての設定を自分で変えられます' },
  selfCustomHint: (direct: string[], asked: string[]) => (direct.length ? `自分で変える：${direct.join('、')}。先に同意を得る：${asked.join('、')}` : 'どの設定も変える前にあなたの同意を得ます'),
  selfTitle: '自分で直接変えられる項目',
  selfNote: 'チェックしていない項目は、変える前にあなたの同意を得ます。',
  selfItems: { figure: 'アバター', scheme: '着せ替え', roam: '歩き回り', snoreSeconds: 'いびきの長さ', sound: 'サウンド', scale: 'サイズ', theme: 'テーマ', hoverButtons: 'ホバーボタン', user: 'あなたの呼び名' },
  popupSave: '保存',
  popupCancel: 'キャンセル',
  actions: { chat: '入力', voice: '音声入力', roam: '歩き回り', theme: 'ナイトモード', sound: 'サウンド', dress: '着せ替え', hide: 'ペットを隠す' },
  saved: '保存しました',
  saveFailed: (why: string) => `保存できませんでした：${why}`,
  stats: '匿名の利用統計',
  statsHint: '回数、利用時間、設定を送信します。会話、Key、ファイルは送信しません。',
  statsDoc: '送信するすべての項目',
};
