import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  nav: 'Hábitos',
  language: 'Idioma',
  languageHint: 'La ventana de configuración y las burbujas y el menú de la mascota usan este idioma, y Coo te habla en él. El texto que aún no está traducido se muestra en inglés (el chino tradicional muestra el simplificado).',
  user: 'Cómo llamarte',
  userHint: 'Coo te llama por este nombre.',
  roam: 'Paseos',
  roamFree: 'A menudo',
  roamCalm: 'De vez en cuando',
  roamOff: 'Sin moverse',
  theme: 'Colores',
  themeDark: 'Noche (cuerpo claro)',
  themeLight: 'Día (cuerpo oscuro)',
  scale: 'Tamaño',
  frameRate: 'Velocidad de fotogramas',
  frameRateHint: 'Fotogramas por segundo mientras Coo camina, cuelga del puntero o salta. Por encima de la frecuencia de actualización de la pantalla, se usa la de la pantalla; Sin límite sigue a la pantalla. Más fotogramas usan más CPU y GPU.',
  frameUnlimited: 'Sin límite',
  lockFps: 'Dibujar siempre a esta velocidad',
  lockFpsHint: 'Desactivado: Coo dibuja 30 fotogramas por segundo mientras está de pie, se sienta o duerme, lo que consume menos. Activado: la velocidad de arriba también en reposo.',
  hideFullscreen: 'Ocultar en pantalla completa',
  hideFullscreenHint: 'Coo se aparta mientras un juego, un video o un navegador ocupa toda su pantalla, y vuelve cuando termina la pantalla completa. Una ventana maximizada no cuenta.',
  soundTitle: 'Sonidos',
  sound: 'Reproducir sonidos',
  soundHint: 'El botón de sonido del menú de Coo también cambia esto.',
  soundKinds: 'Por tipo',
  soundKindsHint: 'Un tipo desactivado queda en silencio; el resto suena como siempre. Deja el puntero sobre uno para ver qué sonidos incluye. Los sonidos propios de un paquete de personaje también entran en estos tipos.',
  kinds: {
    move: ['Movimientos', 'Caminar, correr, saltar, aterrizar, salir volando, asentir, negar con la cabeza, girar, marearse, temblar, bailar, mirar alrededor'],
    touch: ['Toque', 'Levantadas, balanceos, caricias, toquecitos'],
    face: ['Caras', 'Feliz, guiño, amor, sorpresa, enojo, tristeza, timidez, bostezo'],
    snore: ['Ronquidos', 'Ronquidos mientras duerme'],
    talk: ['Habla', 'El balbuceo mientras aparece el texto de la burbuja, las tarjetas de opciones al aparecer'],
    ui: ['Botones y avisos', 'Clics en botones, burbujas que se abren, selecciones, inicio y fin de la escucha'],
  },
  snore: 'Roncar durante',
  snoreUnit: 's',
  snoreHint: 'En cada siesta Coo se queda en silencio tras roncar este tiempo; las z siguen flotando. 0 = roncar hasta despertar.',
  remember: 'Recordar dónde está Coo',
  rememberHint: 'Guarda en qué punto horizontal de la pantalla está Coo al cerrar la app; con varias pantallas Coo siempre empieza en la principal.',
  hover: 'Botones al pasar el cursor',
  hoverHint: (n: number) => `Botones junto a Coo mientras el puntero está encima, hasta ${n}.`,
  dblclick: 'Doble clic en Coo para abrir el cuadro de texto',
  statusBubble: 'Mostrar lo que hace Coo',
  statusBubbleHint: 'Una burbuja pequeña sobre Coo muestra cuándo está pensando, revisando archivos de su memoria o usando la computadora. Se muestran los nombres de archivo.',
  wake: 'Modo de respuesta',
  wakeModes: { none: 'Tranquilo', poke: 'Predeterminado', all: 'Activo', custom: 'Personalizado…' },
  wakeHints: { none: 'Los toques quedan anotados y reciben respuesta juntos la próxima vez que hables', poke: 'Solo responde cuando das un toque', all: 'Responde a todos los toques' },
  wakeCustomHint: (kinds: string[]) => `Responde enseguida a: ${kinds.join(', ')}. Los demás toques reciben respuesta juntos la próxima vez que hables`,
  wakeTitle: 'Estos toques tienen respuesta inmediata',
  wakeKinds: { poke: 'Toque', pet: 'Caricia en la cabeza', throw: 'Lanzar', drop: 'Levantar y soltar' },
  self: 'Autoajuste',
  selfModes: { off: 'Prohibido', default: 'Predeterminado', any: 'Todo', custom: 'Personalizado…' },
  selfHints: { off: 'No se pueden cambiar los ajustes por cuenta propia', default: 'Personaje, atuendo, paseos y ronquidos se cambian directamente; tamaño, sonidos, tema, botones al pasar el cursor y cómo llamarte esperan tu consentimiento', any: 'Todos los ajustes se pueden cambiar directamente' },
  selfCustomHint: (direct: string[], asked: string[]) => (direct.length ? `Se cambian directamente: ${direct.join(', ')}. Esperan tu consentimiento: ${asked.join(', ')}` : 'Cada ajuste espera tu consentimiento antes de cambiarse'),
  selfTitle: 'Se pueden cambiar directamente',
  selfNote: 'Lo que no esté marcado espera tu consentimiento antes de cambiarse.',
  selfItems: { figure: 'Personaje', scheme: 'Atuendo', roam: 'Paseos', snoreSeconds: 'Duración del ronquido', sound: 'Sonidos', scale: 'Tamaño', theme: 'Tema', hoverButtons: 'Botones al pasar el cursor', user: 'Cómo llamarte' },
  popupSave: 'Guardar',
  popupCancel: 'Cancelar',
  actions: { chat: 'Escribir', voice: 'Entrada de voz', roam: 'Paseos', theme: 'Modo nocturno', sound: 'Sonidos', dress: 'Vestuario', hide: 'Ocultar mascota' },
  saveFailed: (why: string) => `No se guardó: ${why}`,
  stats: 'Estadísticas de uso anónimas',
  statsHint: 'Envía conteos, tiempo de uso y configuración; nunca conversaciones, API Keys ni archivos.',
  statsDoc: 'Todos los campos que envía',
  groupGeneral: 'General',
  groupBehavior: 'Comportamiento',
  groupDisplay: 'Pantalla',
  statsLabel: 'Estadísticas de uso',
  dblclickLabel: 'Doble clic',
  statusBubbleLabel: 'Burbuja de estado',
  hideFullscreenLabel: 'Pantalla completa',
  rememberLabel: 'Posición',
  soundLabel: 'Sonidos',
};
