import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  nav: '習慣',
  settingsTitle: '習慣',
  language: '語言',
  languageHint: '設定視窗、桌寵的氣泡和選單都使用這種語言，Coo 也用它和你說話。還沒有譯文的地方顯示英文（繁體中文顯示簡體）。',
  user: '怎麼稱呼你',
  userHint: 'Coo 會用這個名字叫你。',
  roam: '走動',
  roamFree: '常走動',
  roamCalm: '多待著',
  roamOff: '不亂動',
  theme: '顏色',
  themeDark: '夜間（淺色身體）',
  themeLight: '白天（深色身體）',
  scale: '大小',
  frameRate: '幀率',
  frameRateHint: '走動、被拎著、跳起時每秒畫幾幀。超過顯示器更新率時以顯示器的為準；「不限」就是跟隨顯示器更新率。幀率越高越耗 CPU 和顯示卡。',
  frameUnlimited: '不限',
  lockFps: '一律依這個幀率繪製',
  lockFpsHint: '關閉時 Coo 站著、坐著、睡著每秒畫 30 幀，佔用更少；開啟後靜止時也依上面的幀率繪製。',
  hideFullscreen: '全螢幕時自動隱藏',
  hideFullscreenHint: '玩遊戲、看全螢幕影片、瀏覽器全螢幕時 Coo 先躲起來，離開全螢幕再出來。最大化的視窗不算全螢幕。',
  soundTitle: '音效',
  sound: '播放音效',
  soundHint: 'Coo 選單裡的音效按鈕切換的也是這個。',
  soundKinds: '分別開關',
  soundKindsHint: '關掉的那一類不再出聲，其餘照常。滑鼠停在一項上能看到它包括哪些聲音。形象包自帶的聲音也歸在這幾類裡。',
  kinds: {
    move: ['動作', '走路、跑、跳、落地、被甩出去、點頭、搖頭、轉圈、頭暈、發抖、跳舞、張望'],
    touch: ['互動', '被拎起來、拎著晃、被摸、被戳'],
    face: ['表情', '開心、眨眼、喜歡、驚訝、生氣、難過、害羞、打哈欠'],
    snore: ['打呼', '睡著時的打呼聲'],
    talk: ['說話', '氣泡文字逐字冒出時的嘰咕聲、選項卡片彈出'],
    ui: ['按鈕與提示', '點按鈕、氣泡彈出、選取、開始和結束聽你說話'],
  },
  snore: '打呼多久',
  snoreUnit: '秒',
  snoreHint: '每次睡著後打呼這麼久就安靜下來，Z 照樣飄。0 = 一直打到醒來。',
  remember: '記住位置',
  rememberHint: '結束時記下 Coo 的橫向位置，下次啟動回到那裡；有多個螢幕時一律在主螢幕上啟動。',
  hover: '懸停按鈕',
  hoverHint: (n: number) => `滑鼠停在 Coo 身上時旁邊出現的按鈕，最多 ${n} 個。`,
  dblclick: '在 Coo 身上點兩下開啟打字框',
  statusBubble: '顯示 Coo 在忙什麼',
  statusBubbleHint: 'Coo 想事情、翻記憶裡的檔案、操作電腦時，頭頂冒個小氣泡寫著在做什麼，會顯示檔名。',
  selfAdjust: '允許 Coo 自己調整',
  selfAdjustHint: 'Coo 可以自己換形象和裝扮、改走動多少；改音效、大小、黑白模式、懸停按鈕和對你的稱呼前會先問你。關閉後這些它都改不了。',
  actions: { chat: '打字', voice: '語音輸入', roam: '行為模式', theme: '夜間模式', sound: '音效', dress: '裝扮', hide: '隱藏桌寵' },
  saved: '已儲存',
  saveFailed: (why: string) => `沒有儲存：${why}`,
  stats: '匿名使用統計',
  statsHint: '傳送使用次數、時長和設定，不含對話內容、Key 和檔案。',
  statsDoc: '具體傳送哪些欄位',
};
