import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  nav: 'Habitudes',
  settingsTitle: 'Habitudes',
  language: 'Langue',
  languageHint: "La fenêtre des paramètres, les bulles et le menu du compagnon utilisent cette langue, et Coo vous parle dans cette langue. Le texte pas encore traduit s'affiche en anglais (le chinois traditionnel s'affiche en simplifié).",
  user: 'Comment vous appeler',
  userHint: 'Coo vous appelle par ce nom.',
  roam: 'Déplacements',
  roamFree: 'Souvent',
  roamCalm: 'De temps en temps',
  roamOff: 'Reste sur place',
  theme: 'Couleurs',
  themeDark: 'Nuit (corps clair)',
  themeLight: 'Jour (corps sombre)',
  scale: 'Taille',
  frameRate: "Fréquence d'images",
  frameRateHint: "Images par seconde quand Coo marche, est porté ou saute. Au-delà de la fréquence de rafraîchissement de l'écran, celle de l'écran s'applique ; Illimitée suit l'écran. Une fréquence plus élevée sollicite davantage le CPU et le GPU.",
  frameUnlimited: 'Illimitée',
  lockFps: 'Toujours dessiner à cette fréquence',
  lockFpsHint: 'Désactivé : Coo dessine 30 images par seconde debout, assis ou endormi, ce qui consomme moins. Activé : la fréquence ci-dessus aussi au repos.',
  hideFullscreen: 'Masquer en plein écran',
  hideFullscreenHint: "Coo s'éclipse quand un jeu, une vidéo ou un navigateur remplit son écran, et revient à la fin du plein écran. Une fenêtre agrandie ne compte pas.",
  soundTitle: 'Sons',
  sound: 'Jouer les sons',
  soundHint: 'Le bouton son du menu de Coo bascule aussi ce réglage.',
  soundKinds: 'Par type',
  soundKindsHint: "Un type désactivé reste muet ; les autres jouent normalement. Posez le pointeur sur un type pour voir les sons qu'il couvre. Les sons propres à un pack de personnage relèvent aussi de ces types.",
  kinds: {
    move: ['Mouvements', 'Marcher, courir, sauter, atterrir, être lancé, hocher la tête, la secouer, tourner, vertige, frissons, danser, regarder autour'],
    touch: ['Contact', 'Être soulevé, balancé, caressé, tapoté'],
    face: ['Expressions', "Joie, clin d'œil, amour, surprise, colère, tristesse, timidité, bâillement"],
    snore: ['Ronflements', 'Ronfle en dormant'],
    talk: ['Parole', "Le babillage à l'apparition du texte des bulles, les cartes de choix qui surgissent"],
    ui: ['Boutons et signaux', "Clics de boutons, ouverture des bulles, sélections, début et fin de l'écoute"],
  },
  snore: 'Ronfler pendant',
  snoreUnit: 's',
  snoreHint: "À chaque sommeil, Coo se tait après avoir ronflé ce temps ; les z continuent de flotter. 0 = ronfler jusqu'au réveil.",
  remember: 'Mémoriser où se tient Coo',
  rememberHint: "Enregistre la position horizontale de Coo quand l'application se ferme ; avec plusieurs écrans, Coo démarre toujours sur l'écran principal.",
  hover: 'Boutons au survol',
  hoverHint: (n: number) => `Boutons à côté de Coo quand le pointeur est posé dessus, jusqu'à ${n}.`,
  dblclick: 'Double-cliquer sur Coo pour ouvrir la zone de saisie',
  statusBubble: 'Montrer ce que fait Coo',
  statusBubbleHint: "Une petite bulle au-dessus de Coo s'affiche quand il réfléchit, parcourt les fichiers de sa mémoire ou utilise l'ordinateur. Les noms de fichiers sont affichés.",
  wake: 'Mode de réponse',
  wakeModes: { none: 'Calme', poke: 'Par défaut', all: 'Réactif', custom: 'Personnalisé…' },
  wakeHints: { none: 'Les contacts attendent et reçoivent une réponse quand vous lui parlez', poke: 'Ne répond que quand on lui donne un petit coup', all: 'Répond à tous les contacts' },
  wakeCustomHint: (kinds: string[]) => `Répond tout de suite à : ${kinds.join(', ')}. Les autres contacts attendent que vous lui parliez`,
  wakeTitle: 'Ces contacts obtiennent une réponse immédiate',
  wakeKinds: { poke: 'Petit coup', pet: 'Caresse sur la tête', throw: 'Lancer', drop: 'Soulever et reposer' },
  self: 'Autoréglage',
  selfModes: { off: 'Interdit', default: 'Par défaut', any: 'Tout', custom: 'Personnalisé…' },
  selfHints: { off: 'Coo ne peut pas changer ses réglages lui-même', default: "Coo change directement son personnage, sa tenue, ses déplacements et ses ronflements ; pour la taille, les sons, le thème, les boutons au survol et la façon de vous appeler, il demande d'abord votre accord", any: 'Coo peut changer directement tous les réglages' },
  selfCustomHint: (direct: string[], asked: string[]) => (direct.length ? `Change directement : ${direct.join(', ')}. Demande d'abord votre accord : ${asked.join(', ')}` : 'Coo demande votre accord avant de changer quoi que ce soit'),
  selfTitle: 'Coo peut changer directement',
  selfNote: "Pour ce qui n'est pas coché, Coo demande votre accord avant de le changer.",
  selfItems: { figure: 'Personnage', scheme: 'Tenue', roam: 'Déplacements', snoreSeconds: 'Durée des ronflements', sound: 'Sons', scale: 'Taille', theme: 'Thème', hoverButtons: 'Boutons au survol', user: 'Comment vous appeler' },
  popupSave: 'Enregistrer',
  popupCancel: 'Annuler',
  actions: { chat: 'Écrire', voice: 'Saisie vocale', roam: 'Déplacements', theme: 'Mode nuit', sound: 'Sons', dress: 'Habiller', hide: 'Masquer le compagnon' },
  saved: 'Enregistré',
  saveFailed: (why: string) => `Non enregistré : ${why}`,
  stats: "Statistiques d'utilisation anonymes",
  statsHint: "Envoie des comptages, le temps d'utilisation et les réglages ; jamais les conversations, les clés ni les fichiers.",
  statsDoc: 'Tous les champs envoyés',
};
