import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  nav: 'Hábitos',
  settingsTitle: 'Hábitos',
  language: 'Idioma',
  languageHint: 'A janela de configurações e os balões e o menu do pet usam este idioma, e o Coo fala com você nele. Textos ainda não traduzidos aparecem em inglês (o chinês tradicional mostra o simplificado).',
  user: 'Como chamar você',
  userHint: 'O Coo chama você por este nome.',
  roam: 'Passeios',
  roamFree: 'Com frequência',
  roamCalm: 'De vez em quando',
  roamOff: 'Sem se mexer',
  theme: 'Cores',
  themeDark: 'Noite (corpo claro)',
  themeLight: 'Dia (corpo escuro)',
  scale: 'Tamanho',
  frameRate: 'Taxa de quadros',
  frameRateHint: 'Quadros por segundo enquanto o Coo anda, é carregado ou pula. Acima da taxa de atualização da tela, vale a da tela; Sem limite segue a tela. Taxas mais altas usam mais CPU e GPU.',
  frameUnlimited: 'Sem limite',
  lockFps: 'Sempre desenhar nesta taxa',
  lockFpsHint: 'Desligado: o Coo desenha 30 quadros por segundo quando está em pé, sentado ou dormindo, o que gasta menos. Ligado: a taxa acima também em repouso.',
  hideFullscreen: 'Ocultar em tela cheia',
  hideFullscreenHint: 'O Coo sai de cena enquanto um jogo, um vídeo ou um navegador ocupa a tela dele, e volta quando a tela cheia termina. Uma janela maximizada não conta.',
  soundTitle: 'Sons',
  sound: 'Tocar sons',
  soundHint: 'O botão de som no menu do Coo também alterna isto.',
  soundKinds: 'Por tipo',
  soundKindsHint: 'Um tipo desligado fica mudo; os demais tocam normalmente. Deixe o ponteiro sobre um para ver quais sons ele inclui. Os sons próprios de um pacote de personagem também entram nesses tipos.',
  kinds: {
    move: ['Movimentos', 'Andar, correr, pular, aterrissar, ser arremessado, acenar com a cabeça, balançar a cabeça, girar, tontura, tremer, dançar, olhar em volta'],
    touch: ['Toque', 'Ser pego, balançado, acariciado, cutucado'],
    face: ['Expressões', 'Feliz, piscadela, amor, surpresa, raiva, tristeza, timidez, bocejo'],
    snore: ['Ronco', 'Roncos durante o sono'],
    talk: ['Fala', 'O balbucio enquanto o texto do balão aparece, cartões de opção surgindo'],
    ui: ['Botões e avisos', 'Cliques em botões, balões abrindo, seleções, início e fim da escuta'],
  },
  snore: 'Roncar por',
  snoreUnit: 's',
  snoreHint: 'Em cada soneca o Coo fica quieto depois de roncar por esse tempo; os z continuam flutuando. 0 = roncar até acordar.',
  remember: 'Lembrar onde o Coo fica',
  rememberHint: 'Salva em que ponto horizontal da tela o Coo está quando o app fecha; com várias telas, o Coo sempre começa na principal.',
  hover: 'Botões ao passar o mouse',
  hoverHint: (n: number) => `Botões ao lado do Coo enquanto o ponteiro está sobre ele, até ${n}.`,
  dblclick: 'Clique duplo no Coo para abrir a caixa de texto',
  statusBubble: 'Mostrar o que o Coo está fazendo',
  statusBubbleHint: 'Um balãozinho acima do Coo mostra quando ele está pensando, consultando arquivos da memória ou usando o computador. Os nomes dos arquivos aparecem.',
  wake: 'Modo de resposta',
  wakeModes: { none: 'Quieto', poke: 'Padrão', all: 'Ativo', custom: 'Personalizado…' },
  wakeHints: { none: 'Os toques ficam guardados e ele responde a todos quando você falar com ele', poke: 'Só responde quando você cutuca', all: 'Responde a todos os toques' },
  wakeCustomHint: (kinds: string[]) => `Responde na hora a: ${kinds.join(', ')}. Os outros toques esperam até você falar com ele`,
  wakeTitle: 'Estes toques têm resposta na hora',
  wakeKinds: { poke: 'Cutucar', pet: 'Carinho na cabeça', throw: 'Arremessar', drop: 'Levantar e soltar' },
  self: 'Autoajuste',
  selfModes: { off: 'Proibido', default: 'Padrão', any: 'Tudo', custom: 'Personalizado…' },
  selfHints: { off: 'O Coo não pode mudar as próprias configurações', default: 'O Coo muda direto o personagem, o visual, os passeios e o ronco; para tamanho, sons, tema, botões ao passar o mouse e como chama você, ele pede seu consentimento antes', any: 'O Coo pode mudar todas as configurações direto' },
  selfCustomHint: (direct: string[], asked: string[]) => (direct.length ? `Muda direto: ${direct.join(', ')}. Pede seu consentimento antes: ${asked.join(', ')}` : 'O Coo pede seu consentimento antes de mudar qualquer configuração'),
  selfTitle: 'O Coo pode mudar isto direto',
  selfNote: 'No que não estiver marcado, o Coo pede seu consentimento antes de mudar.',
  selfItems: { figure: 'Personagem', scheme: 'Visual', roam: 'Passeios', snoreSeconds: 'Duração do ronco', sound: 'Sons', scale: 'Tamanho', theme: 'Tema', hoverButtons: 'Botões ao passar o mouse', user: 'Como chamar você' },
  popupSave: 'Salvar',
  popupCancel: 'Cancelar',
  actions: { chat: 'Digitar', voice: 'Entrada de voz', roam: 'Passeios', theme: 'Modo noturno', sound: 'Sons', dress: 'Guarda-roupa', hide: 'Ocultar o pet' },
  saved: 'Salvo',
  saveFailed: (why: string) => `Não foi salvo: ${why}`,
  stats: 'Estatísticas de uso anônimas',
  statsHint: 'Envia contagens, tempo de uso e configurações; nunca conversas, API Keys ou arquivos.',
  statsDoc: 'Todos os campos enviados',
};
