import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  nav: 'Abitudini',
  language: 'Lingua',
  languageHint: "La finestra delle impostazioni, i fumetti e il menu dell'animaletto usano questa lingua, e Coo ti parla in questa lingua. Il testo non ancora tradotto appare in inglese (il cinese tradizionale appare in semplificato).",
  user: 'Come chiamarti',
  userHint: 'Coo ti chiama con questo nome.',
  roam: 'Movimento',
  roamFree: 'Spesso',
  roamCalm: 'Ogni tanto',
  roamOff: 'Resta al suo posto',
  theme: 'Colori',
  themeDark: 'Notte (corpo chiaro)',
  themeLight: 'Giorno (corpo scuro)',
  scale: 'Dimensione',
  frameRate: 'Frequenza fotogrammi',
  frameRateHint: 'Fotogrammi al secondo mentre Coo cammina, si fa portare o salta. Oltre la frequenza di aggiornamento dello schermo vale quella dello schermo; Illimitata segue lo schermo. Frequenze più alte usano più CPU e GPU.',
  frameUnlimited: 'Illimitata',
  lockFps: 'Disegna sempre a questa frequenza',
  lockFpsHint: 'Disattivato: Coo disegna 30 fotogrammi al secondo quando sta in piedi, sta a sedere o dorme, e consuma meno. Attivato: la frequenza qui sopra anche quando non si muove.',
  hideFullscreen: 'Nascondi a schermo intero',
  hideFullscreenHint: 'Coo si fa da parte mentre un gioco, un video o un browser riempie il suo schermo, e torna quando lo schermo intero finisce. Una finestra ingrandita non conta.',
  soundTitle: 'Suoni',
  sound: 'Riproduci suoni',
  soundHint: 'Anche il pulsante dei suoni nel menu di Coo attiva e disattiva questa opzione.',
  soundKinds: 'Per tipo',
  soundKindsHint: 'Un tipo disattivato resta muto; gli altri suonano come sempre. Tieni il puntatore su un tipo per vedere quali suoni comprende. Anche i suoni propri di un pacchetto personaggio rientrano in questi tipi.',
  kinds: {
    move: ['Movimento', 'Camminare, correre, saltare, atterrare, volare dopo un lancio, annuire, scuotere la testa, fare piroette, capogiro, brividi, ballare, guardarsi intorno'],
    touch: ['Tocco', 'Sollevamenti, dondolii, carezze, colpetti'],
    face: ['Espressioni', 'Felice, occhiolino, amore, sorpresa, rabbia, tristezza, timidezza, sbadiglio'],
    snore: ['Russare', 'Russa mentre dorme'],
    talk: ['Parlare', 'Il borbottio mentre appare il testo del fumetto, le schede di scelta che spuntano'],
    ui: ['Pulsanti e segnali', "Clic sui pulsanti, apertura dei fumetti, selezioni, inizio e fine dell'ascolto"],
  },
  snore: 'Russa per',
  snoreUnit: 's',
  snoreHint: 'In ogni sonno Coo smette di russare dopo questo tempo; le z continuano a fluttuare. 0 = russa fino al risveglio.',
  remember: 'Ricorda dove sta Coo',
  rememberHint: "Salva la posizione orizzontale di Coo quando l'app si chiude; con più schermi Coo parte sempre su quello principale.",
  hover: 'Pulsanti al passaggio',
  hoverHint: (n: number) => `Pulsanti accanto a Coo mentre il puntatore ci resta sopra, fino a ${n}.`,
  dblclick: 'Doppio clic su Coo per aprire la casella di testo',
  statusBubble: 'Mostra cosa sta facendo Coo',
  statusBubbleHint: 'Un piccolo fumetto sopra Coo appare quando pensa, sfoglia i file della sua memoria o usa il computer. I nomi dei file vengono mostrati.',
  wake: 'Modalità di risposta',
  wakeModes: { none: 'Tranquillo', poke: 'Predefinito', all: 'Attivo', custom: 'Personalizzato…' },
  wakeHints: { none: 'I tocchi vengono annotati e ricevono risposta tutti insieme quando parli tu', poke: 'Risponde solo ai colpetti', all: 'Risponde a tutti i tocchi' },
  wakeCustomHint: (kinds: string[]) => `Risponde subito a: ${kinds.join(', ')}. Gli altri tocchi ricevono risposta tutti insieme quando parli tu`,
  wakeTitle: 'Questi tocchi ricevono subito una risposta',
  wakeKinds: { poke: 'Punzecchiare', pet: 'Carezza sulla testa', throw: 'Lanciare', drop: 'Sollevare e posare' },
  self: 'Autoregolazione',
  selfModes: { off: 'Vietato', default: 'Predefinito', any: 'Tutto', custom: 'Personalizzato…' },
  selfHints: { off: 'Le impostazioni non si possono cambiare in autonomia', default: 'Personaggio, abiti, movimento e russare si cambiano direttamente; per dimensione, suoni, tema, pulsanti al passaggio e come chiamarti serve prima il tuo consenso', any: 'Tutte le impostazioni si possono cambiare direttamente' },
  selfCustomHint: (direct: string[], asked: string[]) => (direct.length ? `Si cambiano direttamente: ${direct.join(', ')}. Serve prima il tuo consenso: ${asked.join(', ')}` : 'Ogni impostazione si cambia solo dopo il tuo consenso'),
  selfTitle: 'Si possono cambiare direttamente',
  selfNote: 'Le voci non spuntate si cambiano solo dopo il tuo consenso.',
  selfItems: { figure: 'Personaggio', scheme: 'Abiti', roam: 'Movimento', snoreSeconds: 'Durata del russare', sound: 'Suoni', scale: 'Dimensione', theme: 'Tema', hoverButtons: 'Pulsanti al passaggio', user: 'Come chiamarti' },
  popupSave: 'Salva',
  popupCancel: 'Annulla',
  actions: { chat: 'Scrivi', voice: 'Input vocale', roam: 'Movimento', theme: 'Modalità notte', sound: 'Suoni', dress: 'Guardaroba', hide: "Nascondi l'animaletto" },
  saved: 'Salvato',
  saveFailed: (why: string) => `Non salvato: ${why}`,
  stats: "Statistiche d'uso anonime",
  statsHint: "Invia conteggi, tempo d'uso e impostazioni; mai conversazioni, chiavi o file.",
  statsDoc: 'Tutti i campi inviati',
  groupGeneral: 'Generale',
  groupBehavior: 'Comportamento',
  groupDisplay: 'Visualizzazione',
  statsLabel: "Statistiche d'uso",
  dblclickLabel: 'Doppio clic',
  statusBubbleLabel: 'Fumetto di stato',
  hideFullscreenLabel: 'Schermo intero',
  rememberLabel: 'Posizione',
  soundLabel: 'Suoni',
};
