import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  nav: 'Habitudes',
  language: 'Langue',
  languageHint: "La fenêtre des paramètres, les bulles et le menu du compagnon utilisent cette langue, et Coo vous parle dans cette langue. Le texte pas encore traduit s'affiche en anglais (le chinois traditionnel s'affiche en simplifié).",
  user: 'Comment vous appeler',
  userHint: 'Coo vous appelle par ce nom.',
  roam: 'Déplacements',
  roamFree: 'Souvent',
  roamCalm: 'De temps en temps',
  roamOff: 'Reste sur place',
  theme: 'Couleurs',
  themeDark: 'Nuit (corps clair)',
  themeLight: 'Jour (corps sombre)',
  scale: 'Taille',
  frameRate: "Fréquence d'images",
  frameRateHint: "Images par seconde quand Coo marche, saute ou se fait porter. Au-delà de la fréquence de rafraîchissement de l'écran, celle de l'écran s'applique ; Illimitée suit l'écran. Une fréquence plus élevée sollicite davantage le CPU et le GPU.",
  frameUnlimited: 'Illimitée',
  lockFps: 'Toujours dessiner à cette fréquence',
  lockFpsHint: "Désactivé : 30 images par seconde quand Coo se tient debout, s'assoit ou dort, ce qui consomme moins. Activé : la fréquence ci-dessus aussi au repos.",
  hideFullscreen: 'Masquer en plein écran',
  hideFullscreenHint: "Coo s'éclipse quand un jeu, une vidéo ou un navigateur remplit son écran, et revient à la fin du plein écran. Une fenêtre agrandie ne compte pas.",
  soundTitle: 'Sons',
  sound: 'Jouer les sons',
  soundHint: 'Le bouton son du menu de Coo bascule aussi ce réglage.',
  soundKinds: 'Par type',
  soundKindsHint: "Un type désactivé reste muet ; les autres jouent normalement. Posez le pointeur sur un type pour voir les sons qu'il couvre. Les sons propres à un pack de personnage relèvent aussi de ces types.",
  kinds: {
    move: ['Mouvements', 'Marcher, courir, sauter, atterrir, se faire lancer, hocher la tête, la secouer, tourner, vertige, frissons, danser, regarder autour'],
    touch: ['Contact', 'Se faire soulever, balancer, caresser, tapoter'],
    face: ['Expressions', "Joie, clin d'œil, amour, surprise, colère, tristesse, timidité, bâillement"],
    snore: ['Ronflements', 'Ronfle en dormant'],
    talk: ['Parole', "Le babillage à l'apparition du texte des bulles, les cartes de choix qui surgissent"],
    ui: ['Boutons et signaux', "Clics de boutons, ouverture des bulles, sélections, début et fin de l'écoute"],
  },
  snore: 'Ronfler pendant',
  snoreUnit: 's',
  snoreHint: "À chaque sommeil, Coo se tait après avoir ronflé ce temps ; les z continuent de flotter. 0 = ronfler jusqu'au réveil.",
  remember: 'Mémoriser où se tient Coo',
  rememberHint: "Enregistre la position horizontale de Coo quand l'application se ferme ; avec plusieurs écrans, Coo démarre toujours sur l'écran principal.",
  hover: 'Boutons au survol',
  hoverHint: (n: number) => `Boutons à côté de Coo quand le pointeur est posé dessus, jusqu'à ${n}.`,
  dblclick: 'Double-cliquer sur Coo pour ouvrir la zone de saisie',
  statusBubble: 'Montrer ce que fait Coo',
  statusBubbleHint: "Pendant la réflexion, la consultation des fichiers de la mémoire ou l'utilisation de l'ordinateur, une petite bulle s'affiche au-dessus de Coo. Les noms de fichiers sont affichés.",
  wake: 'Mode de réponse',
  wakeModes: { none: 'Calme', poke: 'Par défaut', all: 'Réactif', custom: 'Personnalisé…' },
  wakeHints: { none: 'Les contacts sont notés et reçoivent une réponse groupée la prochaine fois que vous parlez', poke: "Ne répond qu'aux petits coups", all: 'Répond à tous les contacts' },
  wakeCustomHint: (kinds: string[]) => `Réponse immédiate pour : ${kinds.join(', ')}. Les autres contacts reçoivent une réponse groupée la prochaine fois que vous parlez`,
  wakeTitle: 'Ces contacts obtiennent une réponse immédiate',
  wakeKinds: { poke: 'Petit coup', pet: 'Caresse sur la tête', throw: 'Lancer', drop: 'Soulever et reposer' },
  self: 'Autoréglage',
  selfModes: { off: 'Interdit', default: 'Par défaut', any: 'Tout', custom: 'Personnalisé…' },
  selfHints: { off: 'Aucun réglage ne change de sa propre initiative', default: "Personnage, tenue, déplacements et ronflements changent directement ; la taille, les sons, le thème, les boutons au survol et la façon de vous appeler attendent d'abord votre accord", any: 'Tous les réglages peuvent changer directement' },
  selfCustomHint: (direct: string[], asked: string[]) => (direct.length ? `Changement direct : ${direct.join(', ')}. Après votre accord : ${asked.join(', ')}` : "Chaque réglage attend votre accord avant d'être changé"),
  selfTitle: 'Réglages modifiables directement',
  selfNote: "Ce qui n'est pas coché attend votre accord avant d'être changé.",
  selfItems: { figure: 'Personnage', scheme: 'Tenue', roam: 'Déplacements', snoreSeconds: 'Durée des ronflements', sound: 'Sons', scale: 'Taille', theme: 'Thème', hoverButtons: 'Boutons au survol', user: 'Comment vous appeler' },
  popupSave: 'Enregistrer',
  popupCancel: 'Annuler',
  actions: { chat: 'Écrire', voice: 'Saisie vocale', roam: 'Déplacements', theme: 'Mode nuit', sound: 'Sons', dress: 'Habiller', hide: 'Masquer le compagnon' },
  saveFailed: (why: string) => `Non enregistré : ${why}`,
  stats: "Statistiques d'utilisation anonymes",
  statsHint: "Envoie des comptages, le temps d'utilisation et les réglages ; jamais les conversations, les clés ni les fichiers.",
  statsDoc: 'Tous les champs envoyés',
  groupGeneral: 'Général',
  groupBehavior: 'Comportement',
  groupDisplay: 'Affichage',
  statsLabel: "Statistiques d'utilisation",
  dblclickLabel: 'Double-clic',
  statusBubbleLabel: "Bulle d'état",
  hideFullscreenLabel: 'Plein écran',
  rememberLabel: 'Position',
  soundLabel: 'Sons',
};
